//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.17 at 12:25:26 PM IST 
//


package com.iexceed.esoko.jaxb.agents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for agentdetailsResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="agentdetailsResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="agentdetailsRes" type="{http://www.iexceed.com/agentdetails}agentdetailsRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "agentdetailsRes"
})
@XmlRootElement(name = "agentdetailsResWrap")
public class AgentdetailsResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/agentdetails", required = true)
    protected AgentdetailsRes agentdetailsRes;

    /**
     * Gets the value of the agentdetailsRes property.
     * 
     * @return
     *     possible object is
     *     {@link AgentdetailsRes }
     *     
     */
    public AgentdetailsRes getAgentdetailsRes() {
        return agentdetailsRes;
    }

    /**
     * Sets the value of the agentdetailsRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentdetailsRes }
     *     
     */
    public void setAgentdetailsRes(AgentdetailsRes value) {
        this.agentdetailsRes = value;
    }

}
