//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.28 at 06:37:13 PM IST 
//


package com.iexceed.esoko.jaxb.agents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for saveForMultipleResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="saveForMultipleResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="saveForMultipleRes" type="{http://www.iexceed.com/saveForMultiple}saveForMultipleRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "saveForMultipleRes"
})
@XmlRootElement(name = "saveForMultipleResWrap")
public class SaveForMultipleResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/saveForMultiple", required = true)
    protected SaveForMultipleRes saveForMultipleRes;

    /**
     * Gets the value of the saveForMultipleRes property.
     * 
     * @return
     *     possible object is
     *     {@link SaveForMultipleRes }
     *     
     */
    public SaveForMultipleRes getSaveForMultipleRes() {
        return saveForMultipleRes;
    }

    /**
     * Sets the value of the saveForMultipleRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SaveForMultipleRes }
     *     
     */
    public void setSaveForMultipleRes(SaveForMultipleRes value) {
        this.saveForMultipleRes = value;
    }

}
