//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.07 at 06:54:29 PM IST 
//


package com.iexceed.esoko.jaxb.ns;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for modifyShareDtlsResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="modifyShareDtlsResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="modifyShareDtlsRes" type="{http://www.iexceed.com/modifyShareDtlsReq}modifyShareDtlsRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modifyShareDtlsRes"
})
@XmlRootElement(name = "modifyShareDtlsResWrap")
public class ModifyShareDtlsResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/modifyShareDtlsReq", required = true)
    protected ModifyShareDtlsRes modifyShareDtlsRes;

    /**
     * Gets the value of the modifyShareDtlsRes property.
     * 
     * @return
     *     possible object is
     *     {@link ModifyShareDtlsRes }
     *     
     */
    public ModifyShareDtlsRes getModifyShareDtlsRes() {
        return modifyShareDtlsRes;
    }

    /**
     * Sets the value of the modifyShareDtlsRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifyShareDtlsRes }
     *     
     */
    public void setModifyShareDtlsRes(ModifyShareDtlsRes value) {
        this.modifyShareDtlsRes = value;
    }

}
