//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.23 at 02:48:10 PM IST 
//


package com.iexceed.esoko.jaxb.ns;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PRICETYPES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PRICETYPES">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="priceTyeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="selectedValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PRICETYPES", propOrder = {
    "priceTyeId",
    "selectedValue"
})
public class PRICETYPES {

    @XmlElement(namespace = "http://www.iexceed.com/nwkPriceTypeSave", required = true)
    protected String priceTyeId;
    @XmlElement(namespace = "http://www.iexceed.com/nwkPriceTypeSave", required = true)
    protected String selectedValue;

    /**
     * Gets the value of the priceTyeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceTyeId() {
        return priceTyeId;
    }

    /**
     * Sets the value of the priceTyeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceTyeId(String value) {
        this.priceTyeId = value;
    }

    /**
     * Gets the value of the selectedValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectedValue() {
        return selectedValue;
    }

    /**
     * Sets the value of the selectedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectedValue(String value) {
        this.selectedValue = value;
    }

}
