//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.24 at 07:42:18 PM IST 
//


package com.iexceed.esoko.jaxb.ns;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QRSMSDTLS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QRSMSDTLS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="providerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="premium" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="voice" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="premiumVoice" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QRSMSDTLS", propOrder = {
    "providerName",
    "amount",
    "currency",
    "premium",
    "voice",
    "premiumVoice"
})
public class QRSMSDTLS {

    @XmlElement(namespace = "http://www.iexceed.com/queryNwkSMSRates", required = true)
    protected String providerName;
    @XmlElement(namespace = "http://www.iexceed.com/queryNwkSMSRates")
    protected float amount;
    @XmlElement(namespace = "http://www.iexceed.com/queryNwkSMSRates", required = true)
    protected String currency;
    @XmlElement(namespace = "http://www.iexceed.com/queryNwkSMSRates")
    protected float premium;
    @XmlElement(namespace = "http://www.iexceed.com/queryNwkSMSRates")
    protected float voice;
    @XmlElement(namespace = "http://www.iexceed.com/queryNwkSMSRates")
    protected float premiumVoice;

    /**
     * Gets the value of the providerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * Sets the value of the providerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderName(String value) {
        this.providerName = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public float getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(float value) {
        this.amount = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the premium property.
     * 
     */
    public float getPremium() {
        return premium;
    }

    /**
     * Sets the value of the premium property.
     * 
     */
    public void setPremium(float value) {
        this.premium = value;
    }

    /**
     * Gets the value of the voice property.
     * 
     */
    public float getVoice() {
        return voice;
    }

    /**
     * Sets the value of the voice property.
     * 
     */
    public void setVoice(float value) {
        this.voice = value;
    }

    /**
     * Gets the value of the premiumVoice property.
     * 
     */
    public float getPremiumVoice() {
        return premiumVoice;
    }

    /**
     * Sets the value of the premiumVoice property.
     * 
     */
    public void setPremiumVoice(float value) {
        this.premiumVoice = value;
    }

}
