//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.12 at 12:16:37 PM IST 
//


package com.iexceed.esoko.jaxb.ns;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QRYPROFILEDTLS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QRYPROFILEDTLS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="profile_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="no_of_fields" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bioData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QRYPROFILEDTLS", propOrder = {
    "profileId",
    "noOfFields",
    "bioData"
})
public class QRYPROFILEDTLS {

    @XmlElement(name = "profile_id", namespace = "http://www.iexceed.com/queryProfileDetails", required = true)
    protected String profileId;
    @XmlElement(name = "no_of_fields", namespace = "http://www.iexceed.com/queryProfileDetails")
    protected int noOfFields;
    @XmlElement(namespace = "http://www.iexceed.com/queryProfileDetails", required = true)
    protected String bioData;

    /**
     * Gets the value of the profileId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileId() {
        return profileId;
    }

    /**
     * Sets the value of the profileId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileId(String value) {
        this.profileId = value;
    }

    /**
     * Gets the value of the noOfFields property.
     * 
     */
    public int getNoOfFields() {
        return noOfFields;
    }

    /**
     * Sets the value of the noOfFields property.
     * 
     */
    public void setNoOfFields(int value) {
        this.noOfFields = value;
    }

    /**
     * Gets the value of the bioData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBioData() {
        return bioData;
    }

    /**
     * Sets the value of the bioData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBioData(String value) {
        this.bioData = value;
    }

}
