//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.30 at 02:48:13 PM IST 
//


package com.iexceed.esoko.jaxb.ns;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queryNwkSmsCodesResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="queryNwkSmsCodesResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="queryNwkSmsCodesRes" type="{http://www.iexceed.com/queryNwkSmsCodes}queryNwkSmsCodesRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queryNwkSmsCodesRes"
})
@XmlRootElement(name = "queryNwkSmsCodesResWrap")
public class QueryNwkSmsCodesResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/queryNwkSmsCodes", required = true)
    protected QueryNwkSmsCodesRes queryNwkSmsCodesRes;

    /**
     * Gets the value of the queryNwkSmsCodesRes property.
     * 
     * @return
     *     possible object is
     *     {@link QueryNwkSmsCodesRes }
     *     
     */
    public QueryNwkSmsCodesRes getQueryNwkSmsCodesRes() {
        return queryNwkSmsCodesRes;
    }

    /**
     * Sets the value of the queryNwkSmsCodesRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryNwkSmsCodesRes }
     *     
     */
    public void setQueryNwkSmsCodesRes(QueryNwkSmsCodesRes value) {
        this.queryNwkSmsCodesRes = value;
    }

}
