//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.12 at 09:49:58 AM IST 
//


package com.iexceed.esoko.jaxb.ns;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for querySharingProfileResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="querySharingProfileResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="querySharingProfileRes" type="{http://www.iexceed.com/querySharingProfile}querySharingProfileRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "querySharingProfileRes"
})
@XmlRootElement(name = "querySharingProfileResWrap")
public class QuerySharingProfileResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/querySharingProfile", required = true)
    protected QuerySharingProfileRes querySharingProfileRes;

    /**
     * Gets the value of the querySharingProfileRes property.
     * 
     * @return
     *     possible object is
     *     {@link QuerySharingProfileRes }
     *     
     */
    public QuerySharingProfileRes getQuerySharingProfileRes() {
        return querySharingProfileRes;
    }

    /**
     * Sets the value of the querySharingProfileRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuerySharingProfileRes }
     *     
     */
    public void setQuerySharingProfileRes(QuerySharingProfileRes value) {
        this.querySharingProfileRes = value;
    }

}
