//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.23 at 02:08:49 PM IST 
//


package com.iexceed.esoko.jaxb.ns;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="saveNetworkUserInfoRes" type="{http://www.iexceed.com/saveNetworkUserInfo}saveNetworkUserInfoRes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "saveNetworkUserInfoRes"
})
@XmlRootElement(name = "saveNetworkUserInfoResWrap")
public class SaveNetworkUserInfoResWrap {

    @XmlElement(required = true)
    protected SaveNetworkUserInfoRes saveNetworkUserInfoRes;

    /**
     * Gets the value of the saveNetworkUserInfoRes property.
     * 
     * @return
     *     possible object is
     *     {@link SaveNetworkUserInfoRes }
     *     
     */
    public SaveNetworkUserInfoRes getSaveNetworkUserInfoRes() {
        return saveNetworkUserInfoRes;
    }

    /**
     * Sets the value of the saveNetworkUserInfoRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SaveNetworkUserInfoRes }
     *     
     */
    public void setSaveNetworkUserInfoRes(SaveNetworkUserInfoRes value) {
        this.saveNetworkUserInfoRes = value;
    }

}
