//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.03 at 12:29:20 PM IST 
//


package com.iexceed.esoko.jaxb.ns;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for saveNwkPermissionsReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="saveNwkPermissionsReq">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iexceed.com/Header}Header"/>
 *         &lt;element name="CRPRMSDTLS" type="{http://www.iexceed.com/saveNwkPermissions}CRPRMSDTLS"/>
 *         &lt;element name="CRNETWORKS" type="{http://www.iexceed.com/saveNwkPermissions}CRNETWORKS"/>
 *         &lt;element name="CRAPPS" type="{http://www.iexceed.com/saveNwkPermissions}CRAPPS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "saveNwkPermissionsReq", propOrder = {
    "header",
    "crprmsdtls",
    "crnetworks",
    "crapps"
})
public class SaveNwkPermissionsReq {

    @XmlElement(name = "Header", namespace = "http://www.iexceed.com/saveNwkPermissions", required = true)
    protected Header header;
    @XmlElement(name = "CRPRMSDTLS", namespace = "http://www.iexceed.com/saveNwkPermissions", required = true)
    protected CRPRMSDTLS crprmsdtls;
    @XmlElement(name = "CRNETWORKS", namespace = "http://www.iexceed.com/saveNwkPermissions", required = true)
    protected CRNETWORKS crnetworks;
    @XmlElement(name = "CRAPPS", namespace = "http://www.iexceed.com/saveNwkPermissions", required = true)
    protected CRAPPS crapps;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the crprmsdtls property.
     * 
     * @return
     *     possible object is
     *     {@link CRPRMSDTLS }
     *     
     */
    public CRPRMSDTLS getCRPRMSDTLS() {
        return crprmsdtls;
    }

    /**
     * Sets the value of the crprmsdtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRPRMSDTLS }
     *     
     */
    public void setCRPRMSDTLS(CRPRMSDTLS value) {
        this.crprmsdtls = value;
    }

    /**
     * Gets the value of the crnetworks property.
     * 
     * @return
     *     possible object is
     *     {@link CRNETWORKS }
     *     
     */
    public CRNETWORKS getCRNETWORKS() {
        return crnetworks;
    }

    /**
     * Sets the value of the crnetworks property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRNETWORKS }
     *     
     */
    public void setCRNETWORKS(CRNETWORKS value) {
        this.crnetworks = value;
    }

    /**
     * Gets the value of the crapps property.
     * 
     * @return
     *     possible object is
     *     {@link CRAPPS }
     *     
     */
    public CRAPPS getCRAPPS() {
        return crapps;
    }

    /**
     * Sets the value of the crapps property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRAPPS }
     *     
     */
    public void setCRAPPS(CRAPPS value) {
        this.crapps = value;
    }

}
