//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 11:22:52 AM IST 
//


package com.iexceed.esoko.jaxb.ns;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SHAREITEMS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SHAREITEMS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="shareItem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shareType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shareStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SHAREITEMS", propOrder = {
    "shareItem",
    "shareType",
    "shareStatus"
})
public class SHAREITEMS {

    @XmlElement(namespace = "http://www.iexceed.com/createShareRequest", required = true)
    protected String shareItem;
    @XmlElement(namespace = "http://www.iexceed.com/createShareRequest", required = true)
    protected String shareType;
    @XmlElement(namespace = "http://www.iexceed.com/createShareRequest", required = true)
    protected String shareStatus;

    /**
     * Gets the value of the shareItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareItem() {
        return shareItem;
    }

    /**
     * Sets the value of the shareItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareItem(String value) {
        this.shareItem = value;
    }

    /**
     * Gets the value of the shareType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareType() {
        return shareType;
    }

    /**
     * Sets the value of the shareType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareType(String value) {
        this.shareType = value;
    }

    /**
     * Gets the value of the shareStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareStatus() {
        return shareStatus;
    }

    /**
     * Sets the value of the shareStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareStatus(String value) {
        this.shareStatus = value;
    }

}
