package com.iexceed.esoko.engine.utils;

public enum ERROR_CODE {
	DM_SV_001("DM-SV-001", "E", "Cannot save data to database"), 
	DM_SV_002("DM-SV-002", "E", "Cannot Find Data"), 
	DM_SV_003("DM-SV-003", "E", "Cannot Delete Data"), 
	ES_PK_001("ES-PK-001", "E", "Primary key cannot be empty"), 
	ES_SV_001("ES-SV-001", "S", "Data saved successfully"), 
	ES_SV_002("ES-SV-002", "E", "Unable to save data"), 
	ES_UD_001("ES-UD-001", "S", "Data updated successfully"), 
	ES_UD_002("ES-UD-002", "E", "Unable to update data"), 
	ES_NR_001("ES-NR-001", "E", "No result found"), 
	ES_SC_001("ES-SC-001", "S", "Success"), 
	ES_DT_001("ES-DT-001", "E", "Data type configuration error"), 
	ES_DL_001("ES-DL-001", "S", "Data deleted successfully"), 
	SMS_DP_001("SMS-DP-001", "S", "SMS Codes have been saved successfully"), 
	ES_ER_001("ES-ER-001", "E", "Record already exists"), 
	ES_ER_002("ES-ER-002", "E", "Email address already in use"), 
	ES_ER_003("ES-ER-003", "E", "Mobile number already in use"), 
	ES_ER_004("ES-ER-004", "E", "Mobile number is invalid or not correct"), 
	ES_PK_002("ES-PK-002", "E", "Network Id cannot be empty"), 
	ES_SH_001("ES-SH-001", "S", "Network Sharing suspended successfully"), 
	SS_SUBPR_SV("SS-SUBPR-SV", "S", "Subscription Price Data saved successfully"), 
	SS_SUBPR_UD("SS-SUBPR-ED", "S", "Subscription Price Data updated successfully"), 
	SS_SUBPR_DL("SS-SUBPR-DL", "S", "Subscription Price Data deleted successfully"), 
	SS_SUBLT_SV("SS-SUBLT-SV", "S", "Subscription Limit Data saved successfully"), 
	SS_SUBLT_UD("SS-SUBLT-ED", "S", "Subscription Limit Data updated successfully"), 
	SS_SUBLT_DL("SS-SUBLT-DL", "S", "Subscription Limit Data deleted successfully"),
	SS_SUBIV_DL("SS-SUBIV-DL", "S", "Subscription Invoice Data deleted successfully"),
	SS_SUBPR_ER1("SS-SUBPR-ER1", "E", "Subscription Level cannot be empty"), 
	SS_SUBPR_ER2("SS-SUBPR-ER2", "E", "Subscription Id cannot be empty"), 
	SS_SUBPR_ER3("SS-SUBPR-ER3", "E", "Subscription Type cannot be empty"), 
	INVOICE_NO_ER("INVOICE-NO-ER", "E", "Invoice number cannot be empty"),
	INVOICE_NO_ER_001("INVOICE-NO-ER-001", "E", "Invoice number is invalid or not correct"),

	FRM_NW_ER("FRM-NW-ER", "E", "From Network cannot be empty"), 
	PRC_SV_001("PRC-SV-001", "S", "Price Type saved successfully"), 
	PRC_SV_002("PRC-SV-002", "S", "Price Type deleted successfully"),
	TO_NW_ER("TO-NW-ER", "E", "To Network cannot be empty"), 
	NS_SHR_ER("NS-SHR-ER", "E", "Share Items cannot be empty"), 
	NS_SHR_CR("NS-SHR-CR", "S", "Your request has been sent successfully and is pending approval from $1"), 
	NS_SHR_STP("NS-SHR-STP", "S", "Netwrok Sharing Stopped successfully"), 
	NS_SHR_ED("NS-SHR-ED", "S","Netwrok Sharing Details are Modified successfully"), 
	NS_SHPRF_ED("NS-SHPRF-ED", "S", "Netwrok Sharing Profile Modified successfully"), 
	NS_SHPRF_CR("NS-SHPRF-CR", "S", "Netwrok Sharing Profile Created successfully"), 
	NS_SHPRF_AP("NS-SHPRF-AP", "S", "Netwrok Sharing Details Approved successfully"), 
	RQ_USER_ER("RQ-USER-ER", "E", "User Id cannot be empty"),
	SH_ITEM_ER("SH-ITEM-ER", "E", "Share Item cannot be empty"),
	SH_PRFL_ER("SH-PRFL-ER", "E", "Share ProfileId cannot be empty"),
	PPL_CR_SC("PPL-CR-SC", "S", "$1 has been added to $2 successfully"),
	PPL_CR_FL("PPL-CR-FL", "E", "Unable to add Person"),
	PPL_UD_SC("PPL-UD-SC", "S", "Member edited successfully"),
	PPL_UD_FL("PPL-UD-FL", "E", "Unable to update Person"),
	PPL_NR_001("PPL-NR-001", "I", "There are no people, please contact your network manager or Administators."),
	PPL_NR_002("PPL-NR-002", "I", "No one was found matching your requirements in this Network."),
	PPL_NWK_001("PPL-NWK-001", "S", "$1 person has been removed successfully"),
	PPL_NWK_002("PPL-NWK-002", "S", "$1 people has been removed successfully"),
	PPL_GR_DL("PPL-GR-DL", "S", "Groups has been removed successfully"),
	PPL_GR_ED("PPL-GR-ED", "S", "Group edited successfully!"),
	PPL_GR_001("PPL-GR-001", "E","$1 already exists in your active list of groups. Please choose another name"),
	PPL_GR_002("PPL-GR-002", "S", "$1 is a valid name, good choice."),
	GR_SC_001("GR-SC-001", "S", "$1 person has been added to $2 groups"),
	GR_SC_002("GR-SC-002", "S", "$1 people has been added to $2 groups"),
	GR_NR_001("GR-NR-001", "I", "No one was found matching your requirements in this Group."),
	PPL_GR_CR("PPL-GR-CR", "S", "New group created successfully"),
	GR_RM_001("GR-RM-001", "S", "$1 person has been removed successfully"),
	GR_RM_002("GR-RM-002", "S", "$1 people has been removed successfully"),
	CM_SC_001("CM-SC-001", "S", "Selected Commodities are successfully saved"),
	LC_SC_001("LC-SC-001", "S", "Selected Locations are successfully saved"),
	LC_SC_002("LC-SC-002", "S", "Location Successfully Created"),
	ES_MS_001("ES-MS-001", "S", "Your detail have been updated successfully."),
	ES_MS_002("ES-MS-002", "I", "There are no transactions for this account. Please try again with other filters."),
	ES_MS_003("ES-MS-003", "I", "Sorry, there are no rates configured for this country"),
	OC_SC_001("OC-SC-001", "E", "Selected Occupations are successfully saved"),
	NWK_SPND_SC("NWK-SPND-SC", "I", "Selected Subscription has been suspend successfully"),
	SUB_UPGRD_INVCE("SUB-UPGRD-INVCE", "S", "Selected Subscription has been Upgraded successfully"),
	SUB_UPGRD_INV_ER("SUB-UPGRD-INVCE-ER","E","Subscription unable to upgrade due to insufficient balance"),
	CM_SC_002("CM-SC-002", "S", "Commodity Created Successfully"),
	MS_SC_001("MS-SC-001", "S", "Meaure Created Successfully"),
	MS_SC_002("MS-SC-002", "S", "Meaure Deleted Successfully"),
	RSLR_EMPTY_ER("RSLR-EMPTY-ER", "E", "Reseller Id cannot be empty"),
	RSLR_CR_SC("RSLR-CR-SC", "S", "Reseller details are Created Successfully"),
	RSLR_UP_SC("RSLR-UP-SC", "S", "Reseller details are Updated Successfully"),
	RSLR_DL_SC("RSLR-DL-SC", "S", "Reseller details are Deleted Successfully"),
	RSLR_EX_SC("RSLR-EX-SC", "E", "A Reseller is already associated with the given network"),
	SUB_SUSPEND_SC("SUB-SUSPEND-SC", "S", "Selected Subscription has been Suspended Successfully"),
	SUBR_CR_SC("SUBR-CR-SC", "S", "Subscriber details are Created Successfully"),
	SUBR_UD_SC("SUBR-UD-SC", "S", "Subscriber details are Updated Successfully"),
	SUBR_OF_CR("SUBR-OF-CR", "I", "Upgrade them now and offer $1 credit"),
	AGENT_TEMPLATE_SC("AGENT-TEMPLATE-SC", "S", "Your email has been sent to Esoko successfully, You would be contacted soon. Thank You"),
	AG_CR_SC("AG-CR-SC", "S", "Agent created succesfully"),
	AG_TMP_DL_001("AG-TMP-DL-001", "S", "Template has been deleted successfully"),
	AGENT_TEMPLATE_ED("AGENT-TEMPLATE-ED", "S", "Your email has been sent to Esoko about your template Edit / Update. You would be contacted soon. Thank You"),
	AGENT_STATUS_ED("AGENT-STATUS-ED", "S", "Agent sucessfully Suspended"),
	AGENT_STATUS_ED1("AGENT-STATUS-ED1", "S", "Agent sucessfully Deleted"),
	AGENT_MUL_SV("AGENT-MUL-SV", "S", "Multiple agents sucessully saved"),
	NW_PR_SV("NW-PR-SV", "S", "Price types saved successfully"),
	NW_DT_SV("NW-DT-SV", "S", "Network details updated successfully"),
	NW_PRV_SV("NW-PRV-SV", "S", "Privacy settings saved successfully"),
	NW_PERMS_SV("NW-PERMS-SV", "S","$1's permissions has been updated successfully"),
	USR_DFNW_001("USR-DFNW-001", "S", "$1 is now set as your default network"),
	USR_DL_001("USR-DL-001", "S", "$1 has been deleted from your list of networks"),
	USR_EMAIL_ERR("USR-DL-001", "S", "Email cannot be empty"),
	PUSH_ALERT_SC_001("PSH-ALRT-SC-001", "S", "Alert saved sucessfully"),
	PUSH_ALERT_SC_002("PSH-ALRT-SC-002", "S", "Message sent successfully"),
	PUSH_ALERT_SC_003("PSH-ALRT-SC-003", "S", "Message scheduled to be sent successfully"),
	PUSH_ALERT_SC_004("PSH-ALRT-SC-004", "S", "Activated successfully"),
	PUSH_ALERT_SC_005("PSH-ALRT-SC-005", "S", "Suspended successfully"),
	PUSH_ALERT_SC_006("PSH-ALRT-SC-006", "S", "Deleted successfully"),
	PUSH_ALERT_SC_007("PSH-ALRT-SC-007", "S", "Alert updated sucessfully"),
	PUSH_ALERT_ER_001("PSH-ALRT-ER-001", "E", "Error! Alert could not be saved!"),
	PUSH_ALERT_ER_002("PSH-ALRT-ER-002", "E", "Error! Message could not be send!"),
	PUSH_ALERT_ER_003("PSH-ALRT-ER-003", "E", "Alert name already in use"),
	PUSH_ALERT_ER_004("PSH-ALRT-ER-004", "E", "Tip code already in use"),
	PUSH_ALERT_ER_005("PSH-ALRT-ER-005", "E", "Tip name already in use"),
	PUSH_ALERT_SC_008("PSH-ALRT-SC-008", "S", "Series created sucessfully"),
	PUSH_ALERT_SC_009("PSH-ALRT-SC-009", "S", "Series updated sucessfully"),
	FX_NR_001("FX-NR-001", "E", "No FX Rates Configured for This Date"),
	FX_SC_001("FX-SC-001", "S", "FX Rates Sucessfully Retrieved"),
	AG_UD_SC("AG-UD-SC","S","Agent Updated Sucessfully"),
	NS_SHPRF_RJ("NS-SHPRF-RJ","S","Netwrok Sharing Details Rejected/Cancelled successfully"),
	PUSH_TEMPLATE_SC("PUSH-TEMPLATE-SC", "S", "Push template saved successfully"),
	PUSH_TEMPLATE_ED("PUSH-TEMPLATE-ED", "S", "Template saved successfully"),
	PS_TMP_DL_001("PS-TMP-DL-001", "S", "template deleted successfully"),
	OP_CR_001("OP-CR-001", "E", "MNC/MCC does not exists"),
	OP_CR_002("OP-CR-002", "S", "Operator created successfully"),
	OP_CR_003("OP-CR-003", "S", "Operator deleted successfully"),
	OP_CR_004("OP-CR-004", "S", "Operator edited successfully"),
	OP_CR_005("OP-CR-005", "S", "Gateway switched successfully"),
	OP_CR_006("OP-CR-006", "S", "Rates uploaded successfully"),
	OP_CR_007("OP-CR-007", "E", "Operator already exists"),
	OP_CR_008("OP-CR-008", "E", "Route with provided gateway already exists"),
	GW_CR_001("GW-CR-001", "S", "New Gateway added successfully"),
	GW_CR_002("GW-CR-002", "E", "Gateway name already exists"),
	SENDER_ID_ED("SENDER-ID-ED","S","Sender Id Successfully Updated"),
	SENDER_ID_SC("SENDER-ID-SC","S","Sender Id Successfully Created"),
	SENDER_ID_DL_001("SENDER-ID-001","S","Sender Id Successfully deleted"),
	NEWS_ER_001("NEWS_ER_001", "E","Agent $1 is not allowed to upload news"),
	LIB_ER_001("LIB_ER_001", "E","Agent $1 is not allowed to upload library"),
	NWS_LIB_DEL_SC("NWS-LIB-DEL-SC","S","News/Library sucessfully deleted"),
	NWS_OFF_DEL_SC("NWS-OFF-DEL-SC","S","Offers sucessfully deleted"),
	NWS_PRC_DEL_SC("NWS-PRC-DEL-SC","S","Price upload sucessfully deleted"),
	PPL_ADMIN_ADD_SC("PPL-ADMIN-ADD-SC","S","$1 has been added to Administrators successfully"),
	EMAIL_SC_001("EMAIL-SC-001","S","Email sent successfully"),
	LOC_APPRVL_SC("LOC-APPRVL-SC","S","Location Approved Successfully"),
	LOC_REJ_SC("LOC-REJ-SC","S","Location Rejected Successfully"),
	NWS_PPL_DEL_SC("NWS-PPL-DEL-SC","S","People upload successfully deleted"),
	PPL_APPRVL("PPL-APPRVL","S","People successfully rejected/approved"),
	LIB_APPRVL("LIB-APPRVL","S","Library/News successfully rejected/approved"),
	BIDS_OFFRS_APPRVL("BIDS-OFFRS-APPRVL","S","Bids And Offers successfully rejected/approved"),
	PRICE_APPRVL("PRICE-APPRVL","S","Prices successfully rejected/approved"),
	EDIT_PRICE("EDIT-PRICE","S","Price successfully updated"),
	LIB_UPDT("LIB-UPDT","S","Library/News successfully updated"),
	LOC_UPDT("LOC-UPDT","S","Location successfully updated"),
	CM_APPRVL("CM-APPRVL", "S", "Selected Commodities are successfully approved"),
	CM_DEL("CM-DEL", "S", "Selected Commodities are successfully deleted"),
	SE_TYPE_ER("SE-TYPE-ER","E","Types can't be empty"),
	SE_ALIAS_ER("SE-ALIAS-ER","E","Alias can't be empty"),
	SE_ATTR_ER("SE-ATTR-ER","E","Attributes can't be empty"),
	KEYWORD_EXISTS("KEYWORD-EXISTS","E","Keyword already in use,Please set a unique keyword"),
	KEYWORD_SC("KEYWORD-SC","S","Keyword Successfully Created"),
	KEYWORD_UD("KEYWORD-UD","S","Keyword Edited Successfully"),
	KEYWORD_SUS("KEYWORD-SUS","S","Keyword suspended successfully"),
	KEYWORD_DEL("KEYWORD-DEL","S","Keyword deleted successfully"),
	KEYWORD_ACTIVATE("KEYWORD-ACTIVATE","S","Keyword activated successfully"),
	DEL_INBOX_SC("DEL-INBOX-SC","S","Inbox activity deleted successfully"),
	SIGNUP_SC_001("SIGNUP-SC-001","S","User validated successfully"),
	SIGNUP_ER_001("SIGNUP-ER-001","E","OTP is invalid"),
	SURV_SV_001("SURV-SV-001", "S", "Survey data saved successfully"),
	PRC_SC("PRC-SC", "S", "Your Prices have been successfully submitted to Esoko and are pending approval"),
	OFR_SC("OFR-SC", "S", "Your request has been submitted successfully"),
	NW_SV_001("NW-SV-001", "S", "News item has been uploaded successfully"),
	LIB_SV_001("LIB-SV-001", "S", "Library  item has been uploaded successfully"),
	KEYWORD_ALS_DUP("KEYWORD-ALS-DUP","E","Keyword alias already exists,please set a unique alias"),
	PUSH_ALR_NR("PUSH-ALR-NR","I","No report on alert delivery found"),
	POLL_ES_001("POLL-ES-001","E","Poll name already in use"),
	POLL_ES_002("POLL-ES-002","S","Poll created successfully"),
	POLL_ES_003("POLL-ES-003","S","Poll edited successfully"),
	POLL_ES_004("POLL-ES-004","S","Poll activated successfully"),
	POLL_ES_005("POLL-ES-005","S","Poll suspended successfully"),
	POLL_ES_006("POLL-ES-006","S","Poll deleted successfully"),
	POLL_ES_007("POLL-ES-007","E","$1 is already used as a keyword. Please choose a different keyword."),
	POLL_ES_008("POLL-ES-008","S", "$1 is a valid keyword."),
	FT_TR_001("FT-TR-001", "E", "Password Does Not Match"),
	FT_TR_002("FT-TR-002", "S", "Fund Transfer Done Successfully"), 
	FT_TR_003("FT-TR-003", "E", "Fund Transfer Failed"),
	SURV_NM_ER("SURV-NM-ER", "E", "Survey name cannot be empty"),
	SURV_NR_ER("SURV-NR-ER", "S", "No result found"),
	PHASE_ER("PHASE-ER", "E", "Phase cannot be empty");

	
	public String exCode;
	public String type;
	public String description;

	private ERROR_CODE(String exCode, String type, String description) {
		this.exCode = exCode;
		this.type = type;
		this.description = description;
	}

	public String getCode() {
		return this.toString();
	}

	public String getType() {
		return this.type;
	}

	public String getDescription() {
		return this.description;
	}

	@Override
	public String toString() {
		return (this.exCode.replace('_', '-'));
	}
}
