//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 05:20:01 PM IST 
//


package com.iexceed.esoko.jaxb.se;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for APPDTLS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="APPDTLS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commodity_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="local_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requestor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="major_market" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="picture" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="TYPE" type="{http://www.iexceed.com/approveCommodites}TYPE" maxOccurs="unbounded"/>
 *         &lt;element name="ATTRIBUTES" type="{http://www.iexceed.com/approveCommodites}ATTRIBUTES" maxOccurs="unbounded"/>
 *         &lt;element name="ALIAS" type="{http://www.iexceed.com/approveCommodites}ALIAS" maxOccurs="unbounded"/>
 *         &lt;element name="VARIETY" type="{http://www.iexceed.com/approveCommodites}VARIETY" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "APPDTLS", propOrder = {
    "commodityName",
    "localName",
    "requestor",
    "majorMarket",
    "description",
    "picture",
    "type",
    "attributes",
    "alias",
    "variety"
})
public class APPDTLS {

    @XmlElement(name = "commodity_name", namespace = "http://www.iexceed.com/approveCommodites", required = true)
    protected String commodityName;
    @XmlElement(name = "local_name", namespace = "http://www.iexceed.com/approveCommodites", required = true)
    protected String localName;
    @XmlElement(namespace = "http://www.iexceed.com/approveCommodites", required = true)
    protected String requestor;
    @XmlElement(name = "major_market", namespace = "http://www.iexceed.com/approveCommodites", required = true)
    protected String majorMarket;
    @XmlElement(namespace = "http://www.iexceed.com/approveCommodites", required = true)
    protected String description;
    @XmlElement(namespace = "http://www.iexceed.com/approveCommodites", required = true)
    protected byte[] picture;
    @XmlElement(name = "TYPE", namespace = "http://www.iexceed.com/approveCommodites", required = true)
    protected List<TYPE> type;
    @XmlElement(name = "ATTRIBUTES", namespace = "http://www.iexceed.com/approveCommodites", required = true)
    protected List<ATTRIBUTES> attributes;
    @XmlElement(name = "ALIAS", namespace = "http://www.iexceed.com/approveCommodites", required = true)
    protected List<ALIAS> alias;
    @XmlElement(name = "VARIETY", namespace = "http://www.iexceed.com/approveCommodites", required = true)
    protected List<VARIETY> variety;

    /**
     * Gets the value of the commodityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * Sets the value of the commodityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityName(String value) {
        this.commodityName = value;
    }

    /**
     * Gets the value of the localName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalName() {
        return localName;
    }

    /**
     * Sets the value of the localName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalName(String value) {
        this.localName = value;
    }

    /**
     * Gets the value of the requestor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestor() {
        return requestor;
    }

    /**
     * Sets the value of the requestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestor(String value) {
        this.requestor = value;
    }

    /**
     * Gets the value of the majorMarket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMajorMarket() {
        return majorMarket;
    }

    /**
     * Sets the value of the majorMarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMajorMarket(String value) {
        this.majorMarket = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the picture property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPicture() {
        return picture;
    }

    /**
     * Sets the value of the picture property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPicture(byte[] value) {
        this.picture = ((byte[]) value);
    }

    /**
     * Gets the value of the type property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTYPE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TYPE }
     * 
     * 
     */
    public List<TYPE> getTYPE() {
        if (type == null) {
            type = new ArrayList<TYPE>();
        }
        return this.type;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getATTRIBUTES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ATTRIBUTES }
     * 
     * 
     */
    public List<ATTRIBUTES> getATTRIBUTES() {
        if (attributes == null) {
            attributes = new ArrayList<ATTRIBUTES>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the alias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getALIAS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ALIAS }
     * 
     * 
     */
    public List<ALIAS> getALIAS() {
        if (alias == null) {
            alias = new ArrayList<ALIAS>();
        }
        return this.alias;
    }

    /**
     * Gets the value of the variety property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variety property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVARIETY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VARIETY }
     * 
     * 
     */
    public List<VARIETY> getVARIETY() {
        if (variety == null) {
            variety = new ArrayList<VARIETY>();
        }
        return this.variety;
    }

}
