//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.06 at 11:18:21 AM IST 
//


package com.iexceed.esoko.jaxb.se;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CRCOMMDTLS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CRCOMMDTLS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commodityID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="commodityAlias" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rank" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="parentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="global_location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="picture" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="qType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="offLorry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wholesale" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CRCOMMATTDTLS" type="{http://www.iexceed.com/createCommodities}CRCOMMATTDTLS" maxOccurs="unbounded"/>
 *         &lt;element name="CRALSDTLS" type="{http://www.iexceed.com/createCommodities}CRALSDTLS" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CRCOMMDTLS", propOrder = {
    "commodityID",
    "commodityAlias",
    "name",
    "description",
    "type",
    "rank",
    "parentId",
    "globalLocation",
    "picture",
    "qType",
    "offLorry",
    "wholesale",
    "status",
    "crcommattdtls",
    "cralsdtls"
})
public class CRCOMMDTLS {

    @XmlElement(namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected String commodityID;
    @XmlElement(namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected String commodityAlias;
    @XmlElement(namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected String name;
    @XmlElement(namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected String description;
    @XmlElement(namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected String type;
    @XmlElement(namespace = "http://www.iexceed.com/createCommodities")
    protected int rank;
    @XmlElement(namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected String parentId;
    @XmlElement(name = "global_location", namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected String globalLocation;
    @XmlElement(namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected byte[] picture;
    @XmlElement(namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected String qType;
    @XmlElement(namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected String offLorry;
    @XmlElement(namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected String wholesale;
    @XmlElement(namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected String status;
    @XmlElement(name = "CRCOMMATTDTLS", namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected List<CRCOMMATTDTLS> crcommattdtls;
    @XmlElement(name = "CRALSDTLS", namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected List<CRALSDTLS> cralsdtls;

    /**
     * Gets the value of the commodityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityID() {
        return commodityID;
    }

    /**
     * Sets the value of the commodityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityID(String value) {
        this.commodityID = value;
    }

    /**
     * Gets the value of the commodityAlias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityAlias() {
        return commodityAlias;
    }

    /**
     * Sets the value of the commodityAlias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityAlias(String value) {
        this.commodityAlias = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     */
    public int getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     */
    public void setRank(int value) {
        this.rank = value;
    }

    /**
     * Gets the value of the parentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * Sets the value of the parentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentId(String value) {
        this.parentId = value;
    }

    /**
     * Gets the value of the globalLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalLocation() {
        return globalLocation;
    }

    /**
     * Sets the value of the globalLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalLocation(String value) {
        this.globalLocation = value;
    }

    /**
     * Gets the value of the picture property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPicture() {
        return picture;
    }

    /**
     * Sets the value of the picture property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPicture(byte[] value) {
        this.picture = ((byte[]) value);
    }

    /**
     * Gets the value of the qType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQType() {
        return qType;
    }

    /**
     * Sets the value of the qType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQType(String value) {
        this.qType = value;
    }

    /**
     * Gets the value of the offLorry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffLorry() {
        return offLorry;
    }

    /**
     * Sets the value of the offLorry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffLorry(String value) {
        this.offLorry = value;
    }

    /**
     * Gets the value of the wholesale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWholesale() {
        return wholesale;
    }

    /**
     * Sets the value of the wholesale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWholesale(String value) {
        this.wholesale = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the crcommattdtls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crcommattdtls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCRCOMMATTDTLS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CRCOMMATTDTLS }
     * 
     * 
     */
    public List<CRCOMMATTDTLS> getCRCOMMATTDTLS() {
        if (crcommattdtls == null) {
            crcommattdtls = new ArrayList<CRCOMMATTDTLS>();
        }
        return this.crcommattdtls;
    }

    /**
     * Gets the value of the cralsdtls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cralsdtls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCRALSDTLS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CRALSDTLS }
     * 
     * 
     */
    public List<CRALSDTLS> getCRALSDTLS() {
        if (cralsdtls == null) {
            cralsdtls = new ArrayList<CRALSDTLS>();
        }
        return this.cralsdtls;
    }

}
