//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 03:53:58 PM IST 
//


package com.iexceed.esoko.jaxb.se;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for createpriceTypeReqWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="createpriceTypeReqWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="createpriceTypeReq" type="{http://www.iexceed.com/createpriceType}createpriceTypeReq"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "createpriceTypeReq"
})
@XmlRootElement(name = "createpriceTypeReqWrap")
public class CreatepriceTypeReqWrap {

    @XmlElement(namespace = "http://www.iexceed.com/createpriceType", required = true)
    protected CreatepriceTypeReq createpriceTypeReq;

    /**
     * Gets the value of the createpriceTypeReq property.
     * 
     * @return
     *     possible object is
     *     {@link CreatepriceTypeReq }
     *     
     */
    public CreatepriceTypeReq getCreatepriceTypeReq() {
        return createpriceTypeReq;
    }

    /**
     * Sets the value of the createpriceTypeReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreatepriceTypeReq }
     *     
     */
    public void setCreatepriceTypeReq(CreatepriceTypeReq value) {
        this.createpriceTypeReq = value;
    }

}
