//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 03:53:58 PM IST 
//


package com.iexceed.esoko.jaxb.se;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for createpriceTypeResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="createpriceTypeResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="createpriceTypeRes" type="{http://www.iexceed.com/createpriceType}createpriceTypeRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "createpriceTypeRes"
})
@XmlRootElement(name = "createpriceTypeResWrap")
public class CreatepriceTypeResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/createpriceType", required = true)
    protected CreatepriceTypeRes createpriceTypeRes;

    /**
     * Gets the value of the createpriceTypeRes property.
     * 
     * @return
     *     possible object is
     *     {@link CreatepriceTypeRes }
     *     
     */
    public CreatepriceTypeRes getCreatepriceTypeRes() {
        return createpriceTypeRes;
    }

    /**
     * Sets the value of the createpriceTypeRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreatepriceTypeRes }
     *     
     */
    public void setCreatepriceTypeRes(CreatepriceTypeRes value) {
        this.createpriceTypeRes = value;
    }

}
