//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.09 at 09:35:19 PM IST 
//


package com.iexceed.esoko.jaxb.se;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for currentlySelectedLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="currentlySelectedLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iexceed.com/Header}Header"/>
 *         &lt;element name="CRSELLOC" type="{http://www.iexceed.com/CurrentlySelectedLocation}CRSELLOC"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "currentlySelectedLocation", propOrder = {
    "header",
    "crselloc"
})
public class CurrentlySelectedLocation {

    @XmlElement(name = "Header", namespace = "http://www.iexceed.com/CurrentlySelectedLocation", required = true)
    protected Header header;
    @XmlElement(name = "CRSELLOC", namespace = "http://www.iexceed.com/CurrentlySelectedLocation", required = true)
    protected CRSELLOC crselloc;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the crselloc property.
     * 
     * @return
     *     possible object is
     *     {@link CRSELLOC }
     *     
     */
    public CRSELLOC getCRSELLOC() {
        return crselloc;
    }

    /**
     * Sets the value of the crselloc property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRSELLOC }
     *     
     */
    public void setCRSELLOC(CRSELLOC value) {
        this.crselloc = value;
    }

}
