//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.11 at 04:55:04 PM IST 
//


package com.iexceed.esoko.jaxb.se;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deleteMeasureResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="deleteMeasureResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="deleteMeasureRes" type="{http://www.iexceed.com/deleteMeasure}deleteMeasureRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deleteMeasureRes"
})
@XmlRootElement(name = "deleteMeasureResWrap")
public class DeleteMeasureResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/deleteMeasure", required = true)
    protected DeleteMeasureRes deleteMeasureRes;

    /**
     * Gets the value of the deleteMeasureRes property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteMeasureRes }
     *     
     */
    public DeleteMeasureRes getDeleteMeasureRes() {
        return deleteMeasureRes;
    }

    /**
     * Sets the value of the deleteMeasureRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteMeasureRes }
     *     
     */
    public void setDeleteMeasureRes(DeleteMeasureRes value) {
        this.deleteMeasureRes = value;
    }

}
