//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.17 at 12:06:04 PM IST 
//


package com.iexceed.esoko.jaxb.se;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mapCommoditiesReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mapCommoditiesReq">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iexceed.com/Header}Header"/>
 *         &lt;element name="MPCOMMDTLS" type="{http://www.iexceed.com/createCommodities}MPCOMMDTLS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mapCommoditiesReq", propOrder = {
    "header",
    "mpcommdtls"
})
public class MapCommoditiesReq {

    @XmlElement(name = "Header", namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected Header header;
    @XmlElement(name = "MPCOMMDTLS", namespace = "http://www.iexceed.com/createCommodities", required = true)
    protected MPCOMMDTLS mpcommdtls;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the mpcommdtls property.
     * 
     * @return
     *     possible object is
     *     {@link MPCOMMDTLS }
     *     
     */
    public MPCOMMDTLS getMPCOMMDTLS() {
        return mpcommdtls;
    }

    /**
     * Sets the value of the mpcommdtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link MPCOMMDTLS }
     *     
     */
    public void setMPCOMMDTLS(MPCOMMDTLS value) {
        this.mpcommdtls = value;
    }

}
