//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 02:23:39 PM IST 
//


package com.iexceed.esoko.jaxb.se;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queryVarietiesRes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="queryVarietiesRes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iexceed.com/Header}Header"/>
 *         &lt;element name="VARDTLS" type="{http://www.iexceed.com/queryVarieties}VARDTLS" maxOccurs="unbounded"/>
 *         &lt;element name="VARALS" type="{http://www.iexceed.com/queryVarieties}VARALS" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "queryVarietiesRes", propOrder = {
    "header",
    "vardtls",
    "varals"
})
public class QueryVarietiesRes {

    @XmlElement(name = "Header", required = true)
    protected Header header;
    @XmlElement(name = "VARDTLS", required = true)
    protected List<VARDTLS> vardtls;
    @XmlElement(name = "VARALS", required = true)
    protected List<VARALS> varals;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the vardtls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vardtls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVARDTLS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VARDTLS }
     * 
     * 
     */
    public List<VARDTLS> getVARDTLS() {
        if (vardtls == null) {
            vardtls = new ArrayList<VARDTLS>();
        }
        return this.vardtls;
    }

    /**
     * Gets the value of the varals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the varals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVARALS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VARALS }
     * 
     * 
     */
    public List<VARALS> getVARALS() {
        if (varals == null) {
            varals = new ArrayList<VARALS>();
        }
        return this.varals;
    }

}
