//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 05:34:53 PM IST 
//


package com.iexceed.esoko.jaxb.se;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for querySysCommoditiesRes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="querySysCommoditiesRes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iexceed.com/Header}Header"/>
 *         &lt;element name="SECTOR" type="{http://www.iexceed.com/querySysCommodities}SECTOR" maxOccurs="unbounded"/>
 *         &lt;element name="COMGRP" type="{http://www.iexceed.com/querySysCommodities}COMGRP" maxOccurs="unbounded"/>
 *         &lt;element name="COMSUBGROUP" type="{http://www.iexceed.com/querySysCommodities}COMSUBGROUP" maxOccurs="unbounded"/>
 *         &lt;element name="COMFAMILY" type="{http://www.iexceed.com/querySysCommodities}COMFAMILY" maxOccurs="unbounded"/>
 *         &lt;element name="QRSYSCOMMDTLS" type="{http://www.iexceed.com/querySysCommodities}QRSYSCOMMDTLS" maxOccurs="unbounded"/>
 *         &lt;element name="COMVARIETY" type="{http://www.iexceed.com/querySysCommodities}COMVARIETY" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "querySysCommoditiesRes", propOrder = {
    "header",
    "sector",
    "comgrp",
    "comsubgroup",
    "comfamily",
    "qrsyscommdtls",
    "comvariety"
})
public class QuerySysCommoditiesRes {

    @XmlElement(name = "Header", namespace = "http://www.iexceed.com/querySysCommodities", required = true)
    protected Header header;
    @XmlElement(name = "SECTOR", namespace = "http://www.iexceed.com/querySysCommodities", required = true)
    protected List<SECTOR> sector;
    @XmlElement(name = "COMGRP", namespace = "http://www.iexceed.com/querySysCommodities", required = true)
    protected List<COMGRP> comgrp;
    @XmlElement(name = "COMSUBGROUP", namespace = "http://www.iexceed.com/querySysCommodities", required = true)
    protected List<COMSUBGROUP> comsubgroup;
    @XmlElement(name = "COMFAMILY", namespace = "http://www.iexceed.com/querySysCommodities", required = true)
    protected List<COMFAMILY> comfamily;
    @XmlElement(name = "QRSYSCOMMDTLS", namespace = "http://www.iexceed.com/querySysCommodities", required = true)
    protected List<QRSYSCOMMDTLS> qrsyscommdtls;
    @XmlElement(name = "COMVARIETY", namespace = "http://www.iexceed.com/querySysCommodities", required = true)
    protected List<COMVARIETY> comvariety;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the sector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSECTOR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SECTOR }
     * 
     * 
     */
    public List<SECTOR> getSECTOR() {
        if (sector == null) {
            sector = new ArrayList<SECTOR>();
        }
        return this.sector;
    }

    /**
     * Gets the value of the comgrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comgrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOMGRP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link COMGRP }
     * 
     * 
     */
    public List<COMGRP> getCOMGRP() {
        if (comgrp == null) {
            comgrp = new ArrayList<COMGRP>();
        }
        return this.comgrp;
    }

    /**
     * Gets the value of the comsubgroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comsubgroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOMSUBGROUP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link COMSUBGROUP }
     * 
     * 
     */
    public List<COMSUBGROUP> getCOMSUBGROUP() {
        if (comsubgroup == null) {
            comsubgroup = new ArrayList<COMSUBGROUP>();
        }
        return this.comsubgroup;
    }

    /**
     * Gets the value of the comfamily property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comfamily property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOMFAMILY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link COMFAMILY }
     * 
     * 
     */
    public List<COMFAMILY> getCOMFAMILY() {
        if (comfamily == null) {
            comfamily = new ArrayList<COMFAMILY>();
        }
        return this.comfamily;
    }

    /**
     * Gets the value of the qrsyscommdtls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qrsyscommdtls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQRSYSCOMMDTLS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QRSYSCOMMDTLS }
     * 
     * 
     */
    public List<QRSYSCOMMDTLS> getQRSYSCOMMDTLS() {
        if (qrsyscommdtls == null) {
            qrsyscommdtls = new ArrayList<QRSYSCOMMDTLS>();
        }
        return this.qrsyscommdtls;
    }

    /**
     * Gets the value of the comvariety property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comvariety property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOMVARIETY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link COMVARIETY }
     * 
     * 
     */
    public List<COMVARIETY> getCOMVARIETY() {
        if (comvariety == null) {
            comvariety = new ArrayList<COMVARIETY>();
        }
        return this.comvariety;
    }

}
