//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.12 at 03:55:19 PM IST 
//


package com.iexceed.esoko.jaxb.people;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addUserAsAdminReqWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="addUserAsAdminReqWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="addUserAsAdminReq" type="{http://www.iexceed.com/addUserAsAdmin}addUserAsAdminReq"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addUserAsAdminReq"
})
@XmlRootElement(name = "addUserAsAdminReqWrap")
public class AddUserAsAdminReqWrap {

    @XmlElement(namespace = "http://www.iexceed.com/addUserAsAdmin", required = true)
    protected AddUserAsAdminReq addUserAsAdminReq;

    /**
     * Gets the value of the addUserAsAdminReq property.
     * 
     * @return
     *     possible object is
     *     {@link AddUserAsAdminReq }
     *     
     */
    public AddUserAsAdminReq getAddUserAsAdminReq() {
        return addUserAsAdminReq;
    }

    /**
     * Sets the value of the addUserAsAdminReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddUserAsAdminReq }
     *     
     */
    public void setAddUserAsAdminReq(AddUserAsAdminReq value) {
        this.addUserAsAdminReq = value;
    }

}
