//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.12 at 03:55:19 PM IST 
//


package com.iexceed.esoko.jaxb.people;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addUserAsAdminReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addUserAsAdminReq">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iexceed.com/Header}Header"/>
 *         &lt;element name="ADDADMINUSR" type="{http://www.iexceed.com/addUserAsAdmin}ADDADMINUSR"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addUserAsAdminReq", propOrder = {
    "header",
    "addadminusr"
})
public class AddUserAsAdminReq {

    @XmlElement(name = "Header", namespace = "http://www.iexceed.com/addUserAsAdmin", required = true)
    protected Header header;
    @XmlElement(name = "ADDADMINUSR", namespace = "http://www.iexceed.com/addUserAsAdmin", required = true)
    protected ADDADMINUSR addadminusr;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the addadminusr property.
     * 
     * @return
     *     possible object is
     *     {@link ADDADMINUSR }
     *     
     */
    public ADDADMINUSR getADDADMINUSR() {
        return addadminusr;
    }

    /**
     * Sets the value of the addadminusr property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADDADMINUSR }
     *     
     */
    public void setADDADMINUSR(ADDADMINUSR value) {
        this.addadminusr = value;
    }

}
