//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 06:08:52 PM IST 
//


package com.iexceed.esoko.jaxb.people;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for checkEmailResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="checkEmailResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="checkEmailRes" type="{http://www.iexceed.com/checkEmail}checkEmailRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "checkEmailRes"
})
@XmlRootElement(name = "checkEmailResWrap")
public class CheckEmailResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/checkEmail", required = true)
    protected CheckEmailRes checkEmailRes;

    /**
     * Gets the value of the checkEmailRes property.
     * 
     * @return
     *     possible object is
     *     {@link CheckEmailRes }
     *     
     */
    public CheckEmailRes getCheckEmailRes() {
        return checkEmailRes;
    }

    /**
     * Sets the value of the checkEmailRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckEmailRes }
     *     
     */
    public void setCheckEmailRes(CheckEmailRes value) {
        this.checkEmailRes = value;
    }

}
