//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 10:48:32 AM IST 
//


package com.iexceed.esoko.jaxb.people;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for COPYUSERS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="COPYUSERS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="county" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="town" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mob1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mob2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profilePic" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COPYUSERS", propOrder = {
    "firstName",
    "lastName",
    "email",
    "county",
    "town",
    "mob1",
    "mob2",
    "profilePic"
})
public class COPYUSERS {

    @XmlElement(namespace = "http://www.iexceed.com/copyUsersToPeople", required = true)
    protected String firstName;
    @XmlElement(namespace = "http://www.iexceed.com/copyUsersToPeople", required = true)
    protected String lastName;
    @XmlElement(namespace = "http://www.iexceed.com/copyUsersToPeople", required = true)
    protected String email;
    @XmlElement(namespace = "http://www.iexceed.com/copyUsersToPeople", required = true)
    protected String county;
    @XmlElement(namespace = "http://www.iexceed.com/copyUsersToPeople", required = true)
    protected String town;
    @XmlElement(namespace = "http://www.iexceed.com/copyUsersToPeople", required = true)
    protected String mob1;
    @XmlElement(namespace = "http://www.iexceed.com/copyUsersToPeople", required = true)
    protected String mob2;
    @XmlElement(namespace = "http://www.iexceed.com/copyUsersToPeople", required = true)
    protected byte[] profilePic;

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounty(String value) {
        this.county = value;
    }

    /**
     * Gets the value of the town property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTown() {
        return town;
    }

    /**
     * Sets the value of the town property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTown(String value) {
        this.town = value;
    }

    /**
     * Gets the value of the mob1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMob1() {
        return mob1;
    }

    /**
     * Sets the value of the mob1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMob1(String value) {
        this.mob1 = value;
    }

    /**
     * Gets the value of the mob2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMob2() {
        return mob2;
    }

    /**
     * Sets the value of the mob2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMob2(String value) {
        this.mob2 = value;
    }

    /**
     * Gets the value of the profilePic property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getProfilePic() {
        return profilePic;
    }

    /**
     * Sets the value of the profilePic property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setProfilePic(byte[] value) {
        this.profilePic = ((byte[]) value);
    }

}
