//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 05:32:43 PM IST 
//


package com.iexceed.esoko.jaxb.people;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deleteGroupResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="deleteGroupResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="deleteGroupRes" type="{http://www.iexceed.com/deleteGroup}deleteGroupRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deleteGroupRes"
})
@XmlRootElement(name = "deleteGroupResWrap")
public class DeleteGroupResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/deleteGroup", required = true)
    protected DeleteGroupRes deleteGroupRes;

    /**
     * Gets the value of the deleteGroupRes property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteGroupRes }
     *     
     */
    public DeleteGroupRes getDeleteGroupRes() {
        return deleteGroupRes;
    }

    /**
     * Sets the value of the deleteGroupRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteGroupRes }
     *     
     */
    public void setDeleteGroupRes(DeleteGroupRes value) {
        this.deleteGroupRes = value;
    }

}
