//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.05 at 06:07:40 PM IST 
//


package com.iexceed.esoko.jaxb.people;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EDGROUPDTL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EDGROUPDTL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="networkId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="updatedName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="smartGroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="match" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="limit" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="selectedBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RULES" type="{http://www.iexceed.com/editGroup}RULES" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EDGROUPDTL", propOrder = {
    "networkId",
    "groupId",
    "updatedName",
    "smartGroup",
    "match",
    "limit",
    "selectedBy",
    "rules"
})
public class EDGROUPDTL {

    @XmlElement(namespace = "http://www.iexceed.com/editGroup", required = true)
    protected String networkId;
    @XmlElement(namespace = "http://www.iexceed.com/editGroup", required = true)
    protected String groupId;
    @XmlElement(namespace = "http://www.iexceed.com/editGroup", required = true)
    protected String updatedName;
    @XmlElement(namespace = "http://www.iexceed.com/editGroup", required = true)
    protected String smartGroup;
    @XmlElement(namespace = "http://www.iexceed.com/editGroup", required = true)
    protected String match;
    @XmlElement(namespace = "http://www.iexceed.com/editGroup")
    protected long limit;
    @XmlElement(namespace = "http://www.iexceed.com/editGroup", required = true)
    protected String selectedBy;
    @XmlElement(name = "RULES", namespace = "http://www.iexceed.com/editGroup", required = true)
    protected List<RULES> rules;

    /**
     * Gets the value of the networkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkId() {
        return networkId;
    }

    /**
     * Sets the value of the networkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkId(String value) {
        this.networkId = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the updatedName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedName() {
        return updatedName;
    }

    /**
     * Sets the value of the updatedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedName(String value) {
        this.updatedName = value;
    }

    /**
     * Gets the value of the smartGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmartGroup() {
        return smartGroup;
    }

    /**
     * Sets the value of the smartGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmartGroup(String value) {
        this.smartGroup = value;
    }

    /**
     * Gets the value of the match property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatch() {
        return match;
    }

    /**
     * Sets the value of the match property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatch(String value) {
        this.match = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     */
    public long getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     */
    public void setLimit(long value) {
        this.limit = value;
    }

    /**
     * Gets the value of the selectedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectedBy() {
        return selectedBy;
    }

    /**
     * Sets the value of the selectedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectedBy(String value) {
        this.selectedBy = value;
    }

    /**
     * Gets the value of the rules property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rules property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRULES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RULES }
     * 
     * 
     */
    public List<RULES> getRULES() {
        if (rules == null) {
            rules = new ArrayList<RULES>();
        }
        return this.rules;
    }

}
