//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.23 at 12:19:00 PM IST 
//


package com.iexceed.esoko.jaxb.people;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queryPersonResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="queryPersonResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="queryPersonRes" type="{http://www.iexceed.com/queryPerson}queryPersonRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queryPersonRes"
})
@XmlRootElement(name = "queryPersonResWrap")
public class QueryPersonResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/queryPerson", required = true)
    protected QueryPersonRes queryPersonRes;

    /**
     * Gets the value of the queryPersonRes property.
     * 
     * @return
     *     possible object is
     *     {@link QueryPersonRes }
     *     
     */
    public QueryPersonRes getQueryPersonRes() {
        return queryPersonRes;
    }

    /**
     * Sets the value of the queryPersonRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryPersonRes }
     *     
     */
    public void setQueryPersonRes(QueryPersonRes value) {
        this.queryPersonRes = value;
    }

}
