//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 06:21:32 PM IST 
//


package com.iexceed.esoko.jaxb.people;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sendEmailResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="sendEmailResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="sendEmailRes" type="{http://www.iexceed.com/sendEmail}sendEmailRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendEmailRes"
})
@XmlRootElement(name = "sendEmailResWrap")
public class SendEmailResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/sendEmail", required = true)
    protected SendEmailRes sendEmailRes;

    /**
     * Gets the value of the sendEmailRes property.
     * 
     * @return
     *     possible object is
     *     {@link SendEmailRes }
     *     
     */
    public SendEmailRes getSendEmailRes() {
        return sendEmailRes;
    }

    /**
     * Sets the value of the sendEmailRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendEmailRes }
     *     
     */
    public void setSendEmailRes(SendEmailRes value) {
        this.sendEmailRes = value;
    }

}
