//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 05:47:36 PM IST 
//


package com.iexceed.esoko.jaxb.login.usrquery;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for USERDETAIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="USERDETAIL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="town" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="yearOfBirth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="occupations" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="commodities" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="markets" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profilePic" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="networkId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profileCompletion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="networkNameStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="networkPicStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emailValidateStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mobileValidateStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userPicStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ageGenderStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="memberStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currencyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="networkName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "USERDETAIL", propOrder = {
    "firstName",
    "lastName",
    "gender",
    "country",
    "email",
    "phone",
    "town",
    "yearOfBirth",
    "occupations",
    "commodities",
    "markets",
    "profilePic",
    "userID",
    "networkId",
    "profileCompletion",
    "networkNameStatus",
    "networkPicStatus",
    "emailValidateStatus",
    "mobileValidateStatus",
    "userPicStatus",
    "ageGenderStatus",
    "memberStatus",
    "currencyId",
    "networkName"
})
public class USERDETAIL {

    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String firstName;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String lastName;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String gender;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String country;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String email;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String phone;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String town;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String yearOfBirth;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String occupations;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String commodities;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String markets;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected byte[] profilePic;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String userID;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String networkId;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String profileCompletion;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String networkNameStatus;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String networkPicStatus;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String emailValidateStatus;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String mobileValidateStatus;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String userPicStatus;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String ageGenderStatus;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String memberStatus;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String currencyId;
    @XmlElement(namespace = "http://www.iexceed.com/queryEsokoUser", required = true)
    protected String networkName;

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the town property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTown() {
        return town;
    }

    /**
     * Sets the value of the town property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTown(String value) {
        this.town = value;
    }

    /**
     * Gets the value of the yearOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYearOfBirth() {
        return yearOfBirth;
    }

    /**
     * Sets the value of the yearOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearOfBirth(String value) {
        this.yearOfBirth = value;
    }

    /**
     * Gets the value of the occupations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupations() {
        return occupations;
    }

    /**
     * Sets the value of the occupations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupations(String value) {
        this.occupations = value;
    }

    /**
     * Gets the value of the commodities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodities() {
        return commodities;
    }

    /**
     * Sets the value of the commodities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodities(String value) {
        this.commodities = value;
    }

    /**
     * Gets the value of the markets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkets() {
        return markets;
    }

    /**
     * Sets the value of the markets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkets(String value) {
        this.markets = value;
    }

    /**
     * Gets the value of the profilePic property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getProfilePic() {
        return profilePic;
    }

    /**
     * Sets the value of the profilePic property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setProfilePic(byte[] value) {
        this.profilePic = ((byte[]) value);
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserID(String value) {
        this.userID = value;
    }

    /**
     * Gets the value of the networkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkId() {
        return networkId;
    }

    /**
     * Sets the value of the networkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkId(String value) {
        this.networkId = value;
    }

    /**
     * Gets the value of the profileCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileCompletion() {
        return profileCompletion;
    }

    /**
     * Sets the value of the profileCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileCompletion(String value) {
        this.profileCompletion = value;
    }

    /**
     * Gets the value of the networkNameStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkNameStatus() {
        return networkNameStatus;
    }

    /**
     * Sets the value of the networkNameStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkNameStatus(String value) {
        this.networkNameStatus = value;
    }

    /**
     * Gets the value of the networkPicStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkPicStatus() {
        return networkPicStatus;
    }

    /**
     * Sets the value of the networkPicStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkPicStatus(String value) {
        this.networkPicStatus = value;
    }

    /**
     * Gets the value of the emailValidateStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailValidateStatus() {
        return emailValidateStatus;
    }

    /**
     * Sets the value of the emailValidateStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailValidateStatus(String value) {
        this.emailValidateStatus = value;
    }

    /**
     * Gets the value of the mobileValidateStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileValidateStatus() {
        return mobileValidateStatus;
    }

    /**
     * Sets the value of the mobileValidateStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileValidateStatus(String value) {
        this.mobileValidateStatus = value;
    }

    /**
     * Gets the value of the userPicStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserPicStatus() {
        return userPicStatus;
    }

    /**
     * Sets the value of the userPicStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserPicStatus(String value) {
        this.userPicStatus = value;
    }

    /**
     * Gets the value of the ageGenderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeGenderStatus() {
        return ageGenderStatus;
    }

    /**
     * Sets the value of the ageGenderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeGenderStatus(String value) {
        this.ageGenderStatus = value;
    }

    /**
     * Gets the value of the memberStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberStatus() {
        return memberStatus;
    }

    /**
     * Sets the value of the memberStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberStatus(String value) {
        this.memberStatus = value;
    }

    /**
     * Gets the value of the currencyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyId() {
        return currencyId;
    }

    /**
     * Sets the value of the currencyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyId(String value) {
        this.currencyId = value;
    }

    /**
     * Gets the value of the networkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkName() {
        return networkName;
    }

    /**
     * Sets the value of the networkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkName(String value) {
        this.networkName = value;
    }

}
