//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 02:27:58 PM IST 
//


package com.iexceed.esoko.jaxb.ms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QRUSRDTLS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QRUSRDTLS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="birthYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="town" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="occupation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dispCcy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultNwk" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultNwkId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultNwkLoc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultNwkOwner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="privSettings" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profilePic" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="resellerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QRUSRDTLS", propOrder = {
    "name",
    "gender",
    "birthYear",
    "country",
    "town",
    "phone1",
    "phone2",
    "address",
    "email",
    "website",
    "occupation",
    "dispCcy",
    "language",
    "defaultNwk",
    "defaultNwkId",
    "defaultNwkLoc",
    "defaultNwkOwner",
    "privSettings",
    "profilePic",
    "resellerId"
})
public class QRUSRDTLS {

    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String name;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String gender;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String birthYear;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String country;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String town;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String phone1;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String phone2;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String address;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String email;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String website;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String occupation;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String dispCcy;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String language;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String defaultNwk;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String defaultNwkId;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String defaultNwkLoc;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String defaultNwkOwner;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String privSettings;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected byte[] profilePic;
    @XmlElement(namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected String resellerId;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the birthYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthYear() {
        return birthYear;
    }

    /**
     * Sets the value of the birthYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthYear(String value) {
        this.birthYear = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the town property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTown() {
        return town;
    }

    /**
     * Sets the value of the town property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTown(String value) {
        this.town = value;
    }

    /**
     * Gets the value of the phone1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone1() {
        return phone1;
    }

    /**
     * Sets the value of the phone1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone1(String value) {
        this.phone1 = value;
    }

    /**
     * Gets the value of the phone2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone2() {
        return phone2;
    }

    /**
     * Sets the value of the phone2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone2(String value) {
        this.phone2 = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsite(String value) {
        this.website = value;
    }

    /**
     * Gets the value of the occupation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * Sets the value of the occupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupation(String value) {
        this.occupation = value;
    }

    /**
     * Gets the value of the dispCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispCcy() {
        return dispCcy;
    }

    /**
     * Sets the value of the dispCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispCcy(String value) {
        this.dispCcy = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the defaultNwk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultNwk() {
        return defaultNwk;
    }

    /**
     * Sets the value of the defaultNwk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultNwk(String value) {
        this.defaultNwk = value;
    }

    /**
     * Gets the value of the defaultNwkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultNwkId() {
        return defaultNwkId;
    }

    /**
     * Sets the value of the defaultNwkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultNwkId(String value) {
        this.defaultNwkId = value;
    }

    /**
     * Gets the value of the defaultNwkLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultNwkLoc() {
        return defaultNwkLoc;
    }

    /**
     * Sets the value of the defaultNwkLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultNwkLoc(String value) {
        this.defaultNwkLoc = value;
    }

    /**
     * Gets the value of the defaultNwkOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultNwkOwner() {
        return defaultNwkOwner;
    }

    /**
     * Sets the value of the defaultNwkOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultNwkOwner(String value) {
        this.defaultNwkOwner = value;
    }

    /**
     * Gets the value of the privSettings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivSettings() {
        return privSettings;
    }

    /**
     * Sets the value of the privSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivSettings(String value) {
        this.privSettings = value;
    }

    /**
     * Gets the value of the profilePic property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getProfilePic() {
        return profilePic;
    }

    /**
     * Sets the value of the profilePic property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setProfilePic(byte[] value) {
        this.profilePic = ((byte[]) value);
    }

    /**
     * Gets the value of the resellerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResellerId() {
        return resellerId;
    }

    /**
     * Sets the value of the resellerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResellerId(String value) {
        this.resellerId = value;
    }

}
