//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 02:27:58 PM IST 
//


package com.iexceed.esoko.jaxb.ms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queryUserDetailsRes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="queryUserDetailsRes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iexceed.com/Header}Header"/>
 *         &lt;element name="QRUSRDTLS" type="{http://www.iexceed.com/queryUserDetails}QRUSRDTLS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "queryUserDetailsRes", propOrder = {
    "header",
    "qrusrdtls"
})
public class QueryUserDetailsRes {

    @XmlElement(name = "Header", namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected Header header;
    @XmlElement(name = "QRUSRDTLS", namespace = "http://www.iexceed.com/queryUserDetails", required = true)
    protected QRUSRDTLS qrusrdtls;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the qrusrdtls property.
     * 
     * @return
     *     possible object is
     *     {@link QRUSRDTLS }
     *     
     */
    public QRUSRDTLS getQRUSRDTLS() {
        return qrusrdtls;
    }

    /**
     * Sets the value of the qrusrdtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link QRUSRDTLS }
     *     
     */
    public void setQRUSRDTLS(QRUSRDTLS value) {
        this.qrusrdtls = value;
    }

}
