//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 04:12:16 PM IST 
//


package com.iexceed.esoko.jaxb.ms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="saveUserDetailsReq" type="{http://www.iexceed.com/saveUserDetails}saveUserDetailsReq"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "saveUserDetailsReq"
})
@XmlRootElement(name = "saveUserDetailsReqWrap")
public class SaveUserDetailsReqWrap {

    @XmlElement(required = true)
    protected SaveUserDetailsReq saveUserDetailsReq;

    /**
     * Gets the value of the saveUserDetailsReq property.
     * 
     * @return
     *     possible object is
     *     {@link SaveUserDetailsReq }
     *     
     */
    public SaveUserDetailsReq getSaveUserDetailsReq() {
        return saveUserDetailsReq;
    }

    /**
     * Sets the value of the saveUserDetailsReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link SaveUserDetailsReq }
     *     
     */
    public void setSaveUserDetailsReq(SaveUserDetailsReq value) {
        this.saveUserDetailsReq = value;
    }

}
