//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 04:22:49 PM IST 
//


package com.iexceed.esoko.jaxb.db;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for createContactsReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="createContactsReq">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iexceed.com/Header}Header"/>
 *         &lt;element name="CRCONTACTDETAILS" type="{http://www.iexceed.com/createContacts}CRCONTACTDETAILS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createContactsReq", propOrder = {
    "header",
    "crcontactdetails"
})
public class CreateContactsReq {

    @XmlElement(name = "Header", namespace = "http://www.iexceed.com/createContacts", required = true)
    protected Header header;
    @XmlElement(name = "CRCONTACTDETAILS", namespace = "http://www.iexceed.com/createContacts", required = true)
    protected CRCONTACTDETAILS crcontactdetails;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the crcontactdetails property.
     * 
     * @return
     *     possible object is
     *     {@link CRCONTACTDETAILS }
     *     
     */
    public CRCONTACTDETAILS getCRCONTACTDETAILS() {
        return crcontactdetails;
    }

    /**
     * Sets the value of the crcontactdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRCONTACTDETAILS }
     *     
     */
    public void setCRCONTACTDETAILS(CRCONTACTDETAILS value) {
        this.crcontactdetails = value;
    }

}
