//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 05:22:14 PM IST 
//


package com.iexceed.esoko.jaxb.db;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SURVEYDTLS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SURVEYDTLS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="surveyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noOfPositives" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="noOfNegatives" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="noOfSuspensions" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SURVEYDTLS", propOrder = {
    "surveyId",
    "description",
    "noOfPositives",
    "noOfNegatives",
    "noOfSuspensions"
})
public class SURVEYDTLS {

    @XmlElement(namespace = "http://www.iexceed.com/querySurveyStats", required = true)
    protected String surveyId;
    @XmlElement(namespace = "http://www.iexceed.com/querySurveyStats", required = true)
    protected String description;
    @XmlElement(namespace = "http://www.iexceed.com/querySurveyStats")
    protected int noOfPositives;
    @XmlElement(namespace = "http://www.iexceed.com/querySurveyStats")
    protected int noOfNegatives;
    @XmlElement(namespace = "http://www.iexceed.com/querySurveyStats")
    protected int noOfSuspensions;

    /**
     * Gets the value of the surveyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurveyId() {
        return surveyId;
    }

    /**
     * Sets the value of the surveyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurveyId(String value) {
        this.surveyId = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the noOfPositives property.
     * 
     */
    public int getNoOfPositives() {
        return noOfPositives;
    }

    /**
     * Sets the value of the noOfPositives property.
     * 
     */
    public void setNoOfPositives(int value) {
        this.noOfPositives = value;
    }

    /**
     * Gets the value of the noOfNegatives property.
     * 
     */
    public int getNoOfNegatives() {
        return noOfNegatives;
    }

    /**
     * Sets the value of the noOfNegatives property.
     * 
     */
    public void setNoOfNegatives(int value) {
        this.noOfNegatives = value;
    }

    /**
     * Gets the value of the noOfSuspensions property.
     * 
     */
    public int getNoOfSuspensions() {
        return noOfSuspensions;
    }

    /**
     * Sets the value of the noOfSuspensions property.
     * 
     */
    public void setNoOfSuspensions(int value) {
        this.noOfSuspensions = value;
    }

}
