//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 06:19:33 PM IST 
//


package com.iexceed.esoko.jaxb.approval;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for editLocationReqWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="editLocationReqWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="editLocationReq" type="{http://www.iexceed.com/editLocationReq}editLocationReq"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "editLocationReq"
})
@XmlRootElement(name = "editLocationReqWrap")
public class EditLocationReqWrap {

    @XmlElement(namespace = "http://www.iexceed.com/editLocationReq", required = true)
    protected EditLocationReq editLocationReq;

    /**
     * Gets the value of the editLocationReq property.
     * 
     * @return
     *     possible object is
     *     {@link EditLocationReq }
     *     
     */
    public EditLocationReq getEditLocationReq() {
        return editLocationReq;
    }

    /**
     * Sets the value of the editLocationReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditLocationReq }
     *     
     */
    public void setEditLocationReq(EditLocationReq value) {
        this.editLocationReq = value;
    }

}
