//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.24 at 03:03:47 PM IST 
//


package com.iexceed.esoko.jaxb.approval;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for libraryApprovalReqWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="libraryApprovalReqWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="libraryApprovalReq" type="{http://www.iexceed.com/libraryApprovalApproval}libraryApprovalReq"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "libraryApprovalReq"
})
@XmlRootElement(name = "libraryApprovalReqWrap")
public class LibraryApprovalReqWrap {

    @XmlElement(namespace = "http://www.iexceed.com/libraryApprovalApproval", required = true)
    protected LibraryApprovalReq libraryApprovalReq;

    /**
     * Gets the value of the libraryApprovalReq property.
     * 
     * @return
     *     possible object is
     *     {@link LibraryApprovalReq }
     *     
     */
    public LibraryApprovalReq getLibraryApprovalReq() {
        return libraryApprovalReq;
    }

    /**
     * Sets the value of the libraryApprovalReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link LibraryApprovalReq }
     *     
     */
    public void setLibraryApprovalReq(LibraryApprovalReq value) {
        this.libraryApprovalReq = value;
    }

}
