//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.17 at 03:17:43 PM IST 
//


package com.iexceed.esoko.jaxb.approval;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for locationApprovalResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="locationApprovalResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="locationApprovalRes" type="{http://www.iexceed.com/locationApproval}locationApprovalRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "locationApprovalRes"
})
@XmlRootElement(name = "locationApprovalResWrap")
public class LocationApprovalResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/locationApproval", required = true)
    protected LocationApprovalRes locationApprovalRes;

    /**
     * Gets the value of the locationApprovalRes property.
     * 
     * @return
     *     possible object is
     *     {@link LocationApprovalRes }
     *     
     */
    public LocationApprovalRes getLocationApprovalRes() {
        return locationApprovalRes;
    }

    /**
     * Sets the value of the locationApprovalRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationApprovalRes }
     *     
     */
    public void setLocationApprovalRes(LocationApprovalRes value) {
        this.locationApprovalRes = value;
    }

}
