//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.24 at 10:16:40 AM IST 
//


package com.iexceed.esoko.jaxb.approval;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecordStsApprovalResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="RecordStsApprovalResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="RecordStsApprovalRes" type="{http://www.iexceed.com/RecordStsApproval}RecordStsApprovalRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "recordStsApprovalRes"
})
@XmlRootElement(name = "RecordStsApprovalResWrap")
public class RecordStsApprovalResWrap {

    @XmlElement(name = "RecordStsApprovalRes", namespace = "http://www.iexceed.com/RecordStsApproval", required = true)
    protected RecordStsApprovalRes recordStsApprovalRes;

    /**
     * Gets the value of the recordStsApprovalRes property.
     * 
     * @return
     *     possible object is
     *     {@link RecordStsApprovalRes }
     *     
     */
    public RecordStsApprovalRes getRecordStsApprovalRes() {
        return recordStsApprovalRes;
    }

    /**
     * Sets the value of the recordStsApprovalRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordStsApprovalRes }
     *     
     */
    public void setRecordStsApprovalRes(RecordStsApprovalRes value) {
        this.recordStsApprovalRes = value;
    }

}
