//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.31 at 07:13:48 PM IST 
//


package com.iexceed.esoko.jaxb.pushalert;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QRTIPS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QRTIPS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cropTipId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="peopleId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alertName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="recipientCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="recipientDetail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="commodity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QRTIPS", propOrder = {
    "cropTipId",
    "peopleId",
    "alertName",
    "recipientCount",
    "recipientDetail",
    "commodity",
    "category",
    "status"
})
public class QRTIPS {

    @XmlElement(namespace = "http://www.iexceed.com/queryCropTips", required = true)
    protected String cropTipId;
    @XmlElement(namespace = "http://www.iexceed.com/queryCropTips", required = true)
    protected String peopleId;
    @XmlElement(namespace = "http://www.iexceed.com/queryCropTips", required = true)
    protected String alertName;
    @XmlElement(namespace = "http://www.iexceed.com/queryCropTips", required = true)
    protected String recipientCount;
    @XmlElement(namespace = "http://www.iexceed.com/queryCropTips", required = true)
    protected String recipientDetail;
    @XmlElement(namespace = "http://www.iexceed.com/queryCropTips", required = true)
    protected String commodity;
    @XmlElement(namespace = "http://www.iexceed.com/queryCropTips", required = true)
    protected String category;
    @XmlElement(namespace = "http://www.iexceed.com/queryCropTips", required = true)
    protected String status;

    /**
     * Gets the value of the cropTipId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCropTipId() {
        return cropTipId;
    }

    /**
     * Sets the value of the cropTipId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCropTipId(String value) {
        this.cropTipId = value;
    }

    /**
     * Gets the value of the peopleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeopleId() {
        return peopleId;
    }

    /**
     * Sets the value of the peopleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeopleId(String value) {
        this.peopleId = value;
    }

    /**
     * Gets the value of the alertName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertName() {
        return alertName;
    }

    /**
     * Sets the value of the alertName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertName(String value) {
        this.alertName = value;
    }

    /**
     * Gets the value of the recipientCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientCount() {
        return recipientCount;
    }

    /**
     * Sets the value of the recipientCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientCount(String value) {
        this.recipientCount = value;
    }

    /**
     * Gets the value of the recipientDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientDetail() {
        return recipientDetail;
    }

    /**
     * Sets the value of the recipientDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientDetail(String value) {
        this.recipientDetail = value;
    }

    /**
     * Gets the value of the commodity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodity() {
        return commodity;
    }

    /**
     * Sets the value of the commodity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodity(String value) {
        this.commodity = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
