//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 08:04:50 PM IST 
//


package com.iexceed.esoko.jaxb.pushalert;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queryAlertDeliveryResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="queryAlertDeliveryResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="queryAlertDeliveryRes" type="{http://www.iexceed.com/queryAlertDelivery}queryAlertDeliveryRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queryAlertDeliveryRes"
})
@XmlRootElement(name = "queryAlertDeliveryResWrap")
public class QueryAlertDeliveryResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/queryAlertDelivery", required = true)
    protected QueryAlertDeliveryRes queryAlertDeliveryRes;

    /**
     * Gets the value of the queryAlertDeliveryRes property.
     * 
     * @return
     *     possible object is
     *     {@link QueryAlertDeliveryRes }
     *     
     */
    public QueryAlertDeliveryRes getQueryAlertDeliveryRes() {
        return queryAlertDeliveryRes;
    }

    /**
     * Sets the value of the queryAlertDeliveryRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryAlertDeliveryRes }
     *     
     */
    public void setQueryAlertDeliveryRes(QueryAlertDeliveryRes value) {
        this.queryAlertDeliveryRes = value;
    }

}
