//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.24 at 06:28:55 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iexceed.com/queryPoll")
package com.iexceed.esoko.jaxb.smspoll;
