//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.28 at 10:31:37 AM IST 
//


package com.iexceed.esoko.jaxb.smspoll;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pollActionResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="pollActionResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="pollActionRes" type="{http://www.iexceed.com/pollAction}pollActionRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pollActionRes"
})
@XmlRootElement(name = "pollActionResWrap")
public class PollActionResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/pollAction", required = true)
    protected PollActionRes pollActionRes;

    /**
     * Gets the value of the pollActionRes property.
     * 
     * @return
     *     possible object is
     *     {@link PollActionRes }
     *     
     */
    public PollActionRes getPollActionRes() {
        return pollActionRes;
    }

    /**
     * Sets the value of the pollActionRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PollActionRes }
     *     
     */
    public void setPollActionRes(PollActionRes value) {
        this.pollActionRes = value;
    }

}
