//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.24 at 06:28:55 PM IST 
//


package com.iexceed.esoko.jaxb.smspoll;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queryPollResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="queryPollResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="queryPollRes" type="{http://www.iexceed.com/queryPoll}queryPollRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queryPollRes"
})
@XmlRootElement(name = "queryPollResWrap")
public class QueryPollResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/queryPoll", required = true)
    protected QueryPollRes queryPollRes;

    /**
     * Gets the value of the queryPollRes property.
     * 
     * @return
     *     possible object is
     *     {@link QueryPollRes }
     *     
     */
    public QueryPollRes getQueryPollRes() {
        return queryPollRes;
    }

    /**
     * Sets the value of the queryPollRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryPollRes }
     *     
     */
    public void setQueryPollRes(QueryPollRes value) {
        this.queryPollRes = value;
    }

}
