//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 04:25:31 PM IST 
//


package com.iexceed.esoko.jaxb.inbox;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inboxActivityMonitorRes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inboxActivityMonitorRes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iexceed.com/Header}Header"/>
 *         &lt;element name="INBXACTVTYMON" type="{http://www.iexceed.com/inboxActivityMonitor}INBXACTVTYMON" maxOccurs="unbounded"/>
 *         &lt;element name="INBXACTVTYMONCTDATA" type="{http://www.iexceed.com/inboxActivityMonitor}INBXACTVTYMONCTDATA" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inboxActivityMonitorRes", propOrder = {
    "header",
    "inbxactvtymon",
    "inbxactvtymonctdata"
})
public class InboxActivityMonitorRes {

    @XmlElement(name = "Header", namespace = "http://www.iexceed.com/inboxActivityMonitor", required = true)
    protected Header header;
    @XmlElement(name = "INBXACTVTYMON", namespace = "http://www.iexceed.com/inboxActivityMonitor", required = true)
    protected List<INBXACTVTYMON> inbxactvtymon;
    @XmlElement(name = "INBXACTVTYMONCTDATA", namespace = "http://www.iexceed.com/inboxActivityMonitor", required = true)
    protected List<INBXACTVTYMONCTDATA> inbxactvtymonctdata;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the inbxactvtymon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inbxactvtymon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINBXACTVTYMON().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INBXACTVTYMON }
     * 
     * 
     */
    public List<INBXACTVTYMON> getINBXACTVTYMON() {
        if (inbxactvtymon == null) {
            inbxactvtymon = new ArrayList<INBXACTVTYMON>();
        }
        return this.inbxactvtymon;
    }

    /**
     * Gets the value of the inbxactvtymonctdata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inbxactvtymonctdata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINBXACTVTYMONCTDATA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INBXACTVTYMONCTDATA }
     * 
     * 
     */
    public List<INBXACTVTYMONCTDATA> getINBXACTVTYMONCTDATA() {
        if (inbxactvtymonctdata == null) {
            inbxactvtymonctdata = new ArrayList<INBXACTVTYMONCTDATA>();
        }
        return this.inbxactvtymonctdata;
    }

}
