//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 04:25:31 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iexceed.com/inboxActivityMonitor")
package com.iexceed.esoko.jaxb.inbox;
