//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.27 at 11:17:23 AM IST 
//


package com.iexceed.esoko.jaxb.inbox;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QRSURVEYDETAILS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QRSURVEYDETAILS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="survey_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="survey_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="network_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="total_score" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="secured_score" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QRSRVQUEANS" type="{http://www.iexceed.com/querySurvey}QRSRVQUEANS" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QRSURVEYDETAILS", propOrder = {
    "surveyName",
    "surveyType",
    "phase",
    "networkId",
    "totalScore",
    "securedScore",
    "qrsrvqueans"
})
public class QRSURVEYDETAILS {

    @XmlElement(name = "survey_name", namespace = "http://www.iexceed.com/querySurvey", required = true)
    protected String surveyName;
    @XmlElement(name = "survey_type", namespace = "http://www.iexceed.com/querySurvey", required = true)
    protected String surveyType;
    @XmlElement(namespace = "http://www.iexceed.com/querySurvey", required = true)
    protected String phase;
    @XmlElement(name = "network_id", namespace = "http://www.iexceed.com/querySurvey", required = true)
    protected String networkId;
    @XmlElement(name = "total_score", namespace = "http://www.iexceed.com/querySurvey", required = true)
    protected String totalScore;
    @XmlElement(name = "secured_score", namespace = "http://www.iexceed.com/querySurvey", required = true)
    protected String securedScore;
    @XmlElement(name = "QRSRVQUEANS", namespace = "http://www.iexceed.com/querySurvey", required = true)
    protected List<QRSRVQUEANS> qrsrvqueans;

    /**
     * Gets the value of the surveyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurveyName() {
        return surveyName;
    }

    /**
     * Sets the value of the surveyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurveyName(String value) {
        this.surveyName = value;
    }

    /**
     * Gets the value of the surveyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurveyType() {
        return surveyType;
    }

    /**
     * Sets the value of the surveyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurveyType(String value) {
        this.surveyType = value;
    }

    /**
     * Gets the value of the phase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase() {
        return phase;
    }

    /**
     * Sets the value of the phase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase(String value) {
        this.phase = value;
    }

    /**
     * Gets the value of the networkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkId() {
        return networkId;
    }

    /**
     * Sets the value of the networkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkId(String value) {
        this.networkId = value;
    }

    /**
     * Gets the value of the totalScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalScore() {
        return totalScore;
    }

    /**
     * Sets the value of the totalScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalScore(String value) {
        this.totalScore = value;
    }

    /**
     * Gets the value of the securedScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecuredScore() {
        return securedScore;
    }

    /**
     * Sets the value of the securedScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecuredScore(String value) {
        this.securedScore = value;
    }

    /**
     * Gets the value of the qrsrvqueans property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qrsrvqueans property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQRSRVQUEANS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QRSRVQUEANS }
     * 
     * 
     */
    public List<QRSRVQUEANS> getQRSRVQUEANS() {
        if (qrsrvqueans == null) {
            qrsrvqueans = new ArrayList<QRSRVQUEANS>();
        }
        return this.qrsrvqueans;
    }

}
