//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.24 at 02:19:56 PM IST 
//


package com.iexceed.esoko.jaxb.ss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for createOperatorReqWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="createOperatorReqWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="createOperatorReq" type="{http://www.iexceed.com/createOperator}createOperatorReq"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "createOperatorReq"
})
@XmlRootElement(name = "createOperatorReqWrap")
public class CreateOperatorReqWrap {

    @XmlElement(namespace = "http://www.iexceed.com/createOperator", required = true)
    protected CreateOperatorReq createOperatorReq;

    /**
     * Gets the value of the createOperatorReq property.
     * 
     * @return
     *     possible object is
     *     {@link CreateOperatorReq }
     *     
     */
    public CreateOperatorReq getCreateOperatorReq() {
        return createOperatorReq;
    }

    /**
     * Sets the value of the createOperatorReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateOperatorReq }
     *     
     */
    public void setCreateOperatorReq(CreateOperatorReq value) {
        this.createOperatorReq = value;
    }

}
