//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 05:47:34 PM IST 
//


package com.iexceed.esoko.jaxb.ss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deleteSenderId complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deleteSenderId">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iexceed.com/Header}Header"/>
 *         &lt;element name="DLSNDID" type="{http://www.iexceed.com/deleteSenderId}DLSNDID"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteSenderId", propOrder = {
    "header",
    "dlsndid"
})
public class DeleteSenderId {

    @XmlElement(name = "Header", namespace = "http://www.iexceed.com/deleteSenderId", required = true)
    protected Header header;
    @XmlElement(name = "DLSNDID", namespace = "http://www.iexceed.com/deleteSenderId", required = true)
    protected DLSNDID dlsndid;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the dlsndid property.
     * 
     * @return
     *     possible object is
     *     {@link DLSNDID }
     *     
     */
    public DLSNDID getDLSNDID() {
        return dlsndid;
    }

    /**
     * Sets the value of the dlsndid property.
     * 
     * @param value
     *     allowed object is
     *     {@link DLSNDID }
     *     
     */
    public void setDLSNDID(DLSNDID value) {
        this.dlsndid = value;
    }

}
