//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.08 at 07:07:32 PM IST 
//


package com.iexceed.esoko.jaxb.ss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deleteResellerDtlsReqWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="deleteResellerDtlsReqWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="deleteResellerDtlsReq" type="{http://www.iexceed.com/deleteResellerDtls}deleteResellerDtlsReq"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deleteResellerDtlsReq"
})
@XmlRootElement(name = "deleteResellerDtlsReqWrap")
public class DeleteResellerDtlsReqWrap {

    @XmlElement(namespace = "http://www.iexceed.com/deleteResellerDtls", required = true)
    protected DeleteResellerDtlsReq deleteResellerDtlsReq;

    /**
     * Gets the value of the deleteResellerDtlsReq property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteResellerDtlsReq }
     *     
     */
    public DeleteResellerDtlsReq getDeleteResellerDtlsReq() {
        return deleteResellerDtlsReq;
    }

    /**
     * Sets the value of the deleteResellerDtlsReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteResellerDtlsReq }
     *     
     */
    public void setDeleteResellerDtlsReq(DeleteResellerDtlsReq value) {
        this.deleteResellerDtlsReq = value;
    }

}
