//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 06:41:23 PM IST 
//


package com.iexceed.esoko.jaxb.ss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deleteSubPricesDtlsResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="deleteSubPricesDtlsResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="deleteSubPricesDtlsRes" type="{http://www.iexceed.com/deleteSubPricesDtls}deleteSubPricesDtlsRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deleteSubPricesDtlsRes"
})
@XmlRootElement(name = "deleteSubPricesDtlsResWrap")
public class DeleteSubPricesDtlsResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/deleteSubPricesDtls", required = true)
    protected DeleteSubPricesDtlsRes deleteSubPricesDtlsRes;

    /**
     * Gets the value of the deleteSubPricesDtlsRes property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteSubPricesDtlsRes }
     *     
     */
    public DeleteSubPricesDtlsRes getDeleteSubPricesDtlsRes() {
        return deleteSubPricesDtlsRes;
    }

    /**
     * Sets the value of the deleteSubPricesDtlsRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteSubPricesDtlsRes }
     *     
     */
    public void setDeleteSubPricesDtlsRes(DeleteSubPricesDtlsRes value) {
        this.deleteSubPricesDtlsRes = value;
    }

}
