//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 02:41:38 PM IST 
//


package com.iexceed.esoko.jaxb.ss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deleteSubLimitsDtlsReqWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="deleteSubLimitsDtlsReqWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="deleteSubLimitsDtlsReq" type="{http://www.iexceed.com/deleteSubLimitsDtls}deleteSubLimitsDtlsReq"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deleteSubLimitsDtlsReq"
})
@XmlRootElement(name = "deleteSubLimitsDtlsReqWrap")
public class DeleteSubLimitsDtlsReqWrap {

    @XmlElement(namespace = "http://www.iexceed.com/deleteSubLimitsDtls", required = true)
    protected DeleteSubLimitsDtlsReq deleteSubLimitsDtlsReq;

    /**
     * Gets the value of the deleteSubLimitsDtlsReq property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteSubLimitsDtlsReq }
     *     
     */
    public DeleteSubLimitsDtlsReq getDeleteSubLimitsDtlsReq() {
        return deleteSubLimitsDtlsReq;
    }

    /**
     * Sets the value of the deleteSubLimitsDtlsReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteSubLimitsDtlsReq }
     *     
     */
    public void setDeleteSubLimitsDtlsReq(DeleteSubLimitsDtlsReq value) {
        this.deleteSubLimitsDtlsReq = value;
    }

}
