//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.31 at 05:15:15 PM IST 
//


package com.iexceed.esoko.jaxb.ss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QRINVCEPYMTDTLS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QRINVCEPYMTDTLS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="invoiceFile" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QRINVCEPYMTDTLS", propOrder = {
    "invoiceFile"
})
public class QRINVCEPYMTDTLS {

    @XmlElement(namespace = "http://www.iexceed.com/queryInvoicePayment", required = true)
    protected byte[] invoiceFile;

    /**
     * Gets the value of the invoiceFile property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getInvoiceFile() {
        return invoiceFile;
    }

    /**
     * Sets the value of the invoiceFile property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setInvoiceFile(byte[] value) {
        this.invoiceFile = ((byte[]) value);
    }

}
