//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.15 at 06:43:58 PM IST 
//


package com.iexceed.esoko.jaxb.ss;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QRYRESELLERPRICESLIST complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QRYRESELLERPRICESLIST">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QRYRESELLERPRICES" type="{http://www.iexceed.com/queryResellerPrices}QRYRESELLERPRICES" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QRYRESELLERPRICESLIST", propOrder = {
    "type",
    "qryresellerprices"
})
public class QRYRESELLERPRICESLIST {

    @XmlElement(namespace = "http://www.iexceed.com/queryResellerPrices", required = true)
    protected String type;
    @XmlElement(name = "QRYRESELLERPRICES", namespace = "http://www.iexceed.com/queryResellerPrices", required = true)
    protected List<QRYRESELLERPRICES> qryresellerprices;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the qryresellerprices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qryresellerprices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQRYRESELLERPRICES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QRYRESELLERPRICES }
     * 
     * 
     */
    public List<QRYRESELLERPRICES> getQRYRESELLERPRICES() {
        if (qryresellerprices == null) {
            qryresellerprices = new ArrayList<QRYRESELLERPRICES>();
        }
        return this.qryresellerprices;
    }

}
