//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.06 at 12:33:38 PM IST 
//


package com.iexceed.esoko.jaxb.ss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queryNetworkLimitRes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="queryNetworkLimitRes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iexceed.com/Header}Header"/>
 *         &lt;element name="QRNWKLIMITDTLS" type="{http://www.iexceed.com/queryNetworkLimit}QRNWKLIMITDTLS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "queryNetworkLimitRes", propOrder = {
    "header",
    "qrnwklimitdtls"
})
public class QueryNetworkLimitRes {

    @XmlElement(name = "Header", namespace = "http://www.iexceed.com/queryNetworkLimit", required = true)
    protected Header header;
    @XmlElement(name = "QRNWKLIMITDTLS", namespace = "http://www.iexceed.com/queryNetworkLimit", required = true)
    protected QRNWKLIMITDTLS qrnwklimitdtls;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the qrnwklimitdtls property.
     * 
     * @return
     *     possible object is
     *     {@link QRNWKLIMITDTLS }
     *     
     */
    public QRNWKLIMITDTLS getQRNWKLIMITDTLS() {
        return qrnwklimitdtls;
    }

    /**
     * Sets the value of the qrnwklimitdtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link QRNWKLIMITDTLS }
     *     
     */
    public void setQRNWKLIMITDTLS(QRNWKLIMITDTLS value) {
        this.qrnwklimitdtls = value;
    }

}
