//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 12:37:00 PM IST 
//


package com.iexceed.esoko.jaxb.ss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for querySubPricingDtlsResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="querySubPricingDtlsResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="querySubPricingDtlsRes" type="{http://www.iexceed.com/querySubPricingDtls}querySubPricingDtlsRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "querySubPricingDtlsRes"
})
@XmlRootElement(name = "querySubPricingDtlsResWrap")
public class QuerySubPricingDtlsResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/querySubPricingDtls", required = true)
    protected QuerySubPricingDtlsRes querySubPricingDtlsRes;

    /**
     * Gets the value of the querySubPricingDtlsRes property.
     * 
     * @return
     *     possible object is
     *     {@link QuerySubPricingDtlsRes }
     *     
     */
    public QuerySubPricingDtlsRes getQuerySubPricingDtlsRes() {
        return querySubPricingDtlsRes;
    }

    /**
     * Sets the value of the querySubPricingDtlsRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuerySubPricingDtlsRes }
     *     
     */
    public void setQuerySubPricingDtlsRes(QuerySubPricingDtlsRes value) {
        this.querySubPricingDtlsRes = value;
    }

}
