//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.29 at 12:04:33 PM IST 
//


package com.iexceed.esoko.jaxb.ss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for querySubscriptionUpgradeResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="querySubscriptionUpgradeResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="querySubscriptionUpgradeRes" type="{http://www.iexceed.com/querySubscriptionUpgrade}querySubscriptionUpgradeRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "querySubscriptionUpgradeRes"
})
@XmlRootElement(name = "querySubscriptionUpgradeResWrap")
public class QuerySubscriptionUpgradeResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/querySubscriptionUpgrade", required = true)
    protected QuerySubscriptionUpgradeRes querySubscriptionUpgradeRes;

    /**
     * Gets the value of the querySubscriptionUpgradeRes property.
     * 
     * @return
     *     possible object is
     *     {@link QuerySubscriptionUpgradeRes }
     *     
     */
    public QuerySubscriptionUpgradeRes getQuerySubscriptionUpgradeRes() {
        return querySubscriptionUpgradeRes;
    }

    /**
     * Sets the value of the querySubscriptionUpgradeRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuerySubscriptionUpgradeRes }
     *     
     */
    public void setQuerySubscriptionUpgradeRes(QuerySubscriptionUpgradeRes value) {
        this.querySubscriptionUpgradeRes = value;
    }

}
