//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.27 at 12:32:42 PM IST 
//


package com.iexceed.esoko.jaxb.ss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queryResellerSubscripInvoicesResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="queryResellerSubscripInvoicesResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="queryResellerSubscripInvoicesRes" type="{http://www.iexceed.com/queryResellerSubscripInvoices}queryResellerSubscripInvoicesRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queryResellerSubscripInvoicesRes"
})
@XmlRootElement(name = "queryResellerSubscripInvoicesResWrap")
public class QueryResellerSubscripInvoicesResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/queryResellerSubscripInvoices", required = true)
    protected QueryResellerSubscripInvoicesRes queryResellerSubscripInvoicesRes;

    /**
     * Gets the value of the queryResellerSubscripInvoicesRes property.
     * 
     * @return
     *     possible object is
     *     {@link QueryResellerSubscripInvoicesRes }
     *     
     */
    public QueryResellerSubscripInvoicesRes getQueryResellerSubscripInvoicesRes() {
        return queryResellerSubscripInvoicesRes;
    }

    /**
     * Sets the value of the queryResellerSubscripInvoicesRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryResellerSubscripInvoicesRes }
     *     
     */
    public void setQueryResellerSubscripInvoicesRes(QueryResellerSubscripInvoicesRes value) {
        this.queryResellerSubscripInvoicesRes = value;
    }

}
