//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 12:51:22 PM IST 
//


package com.iexceed.esoko.jaxb.ss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for querySubLimitsDtlsResWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="querySubLimitsDtlsResWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="querySubLimitsDtlsRes" type="{http://www.iexceed.com/querySubLimitsDtls}querySubLimitsDtlsRes"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "querySubLimitsDtlsRes"
})
@XmlRootElement(name = "querySubLimitsDtlsResWrap")
public class QuerySubLimitsDtlsResWrap {

    @XmlElement(namespace = "http://www.iexceed.com/querySubLimitsDtls", required = true)
    protected QuerySubLimitsDtlsRes querySubLimitsDtlsRes;

    /**
     * Gets the value of the querySubLimitsDtlsRes property.
     * 
     * @return
     *     possible object is
     *     {@link QuerySubLimitsDtlsRes }
     *     
     */
    public QuerySubLimitsDtlsRes getQuerySubLimitsDtlsRes() {
        return querySubLimitsDtlsRes;
    }

    /**
     * Sets the value of the querySubLimitsDtlsRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuerySubLimitsDtlsRes }
     *     
     */
    public void setQuerySubLimitsDtlsRes(QuerySubLimitsDtlsRes value) {
        this.querySubLimitsDtlsRes = value;
    }

}
