//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.31 at 05:15:15 PM IST 
//


package com.iexceed.esoko.jaxb.ss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queryInvoicePaymentRes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="queryInvoicePaymentRes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iexceed.com/Header}Header"/>
 *         &lt;element name="QRINVCEPYMTDTLS" type="{http://www.iexceed.com/queryInvoicePayment}QRINVCEPYMTDTLS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "queryInvoicePaymentRes", propOrder = {
    "header",
    "qrinvcepymtdtls"
})
public class QueryInvoicePaymentRes {

    @XmlElement(name = "Header", namespace = "http://www.iexceed.com/queryInvoicePayment", required = true)
    protected Header header;
    @XmlElement(name = "QRINVCEPYMTDTLS", namespace = "http://www.iexceed.com/queryInvoicePayment", required = true)
    protected QRINVCEPYMTDTLS qrinvcepymtdtls;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the qrinvcepymtdtls property.
     * 
     * @return
     *     possible object is
     *     {@link QRINVCEPYMTDTLS }
     *     
     */
    public QRINVCEPYMTDTLS getQRINVCEPYMTDTLS() {
        return qrinvcepymtdtls;
    }

    /**
     * Sets the value of the qrinvcepymtdtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link QRINVCEPYMTDTLS }
     *     
     */
    public void setQRINVCEPYMTDTLS(QRINVCEPYMTDTLS value) {
        this.qrinvcepymtdtls = value;
    }

}
