//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 11:24:06 AM IST 
//


package com.iexceed.esoko.jaxb.ss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for subscriptionSuspendReqWrap element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="subscriptionSuspendReqWrap">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="subscriptionSuspendReq" type="{http://www.iexceed.com/subscriptionSuspend}subscriptionSuspendReq"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subscriptionSuspendReq"
})
@XmlRootElement(name = "subscriptionSuspendReqWrap")
public class SubscriptionSuspendReqWrap {

    @XmlElement(namespace = "http://www.iexceed.com/subscriptionSuspend", required = true)
    protected SubscriptionSuspendReq subscriptionSuspendReq;

    /**
     * Gets the value of the subscriptionSuspendReq property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionSuspendReq }
     *     
     */
    public SubscriptionSuspendReq getSubscriptionSuspendReq() {
        return subscriptionSuspendReq;
    }

    /**
     * Sets the value of the subscriptionSuspendReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionSuspendReq }
     *     
     */
    public void setSubscriptionSuspendReq(SubscriptionSuspendReq value) {
        this.subscriptionSuspendReq = value;
    }

}
